export type LegalSection = { title: string; paragraphs?: string[]; bullets?: string[] };
export type LegalDocument = { title: string; summary: string; version: string; sections: LegalSection[] };

export const legalDocuments: Record<string, LegalDocument> = {
  terms: {
    title: "Terms of Service", version: "2026-08-29", summary: "Rules for accessing and using the Xspace collaboration service.",
    sections: [
      {title:"1. Agreement and service provider",paragraphs:["These Terms form an agreement between the customer or workspace owner that accepts them and Cankonix Technology (\"Cankonix\", \"we\", or \"us\"), the operator of Xspace. The person accepting confirms that they have authority to bind the customer.","Xspace provides tenant-scoped meetings, messaging, rooms, files, recordings, directory, administration, identity, governance, and related support features. Features and limits depend on the selected plan."]},
      {title:"2. Accounts and customer administration",bullets:["Customers are responsible for authorized users, workspace configuration, role assignment, credentials, and lawful instructions given through administrators.","Users must provide accurate account information, protect credentials, enable available security controls where appropriate, and promptly report suspected compromise.","A workspace owner controls customer content and may access, retain, export, restrict, or delete it according to workspace policy and law."]},
      {title:"3. Acceptable use",paragraphs:["Xspace may not be used to violate law, infringe rights, distribute malware, interfere with service integrity, bypass security or quotas, conduct unauthorized surveillance, or record a person without required notice and lawful authority."],bullets:["Do not upload illegal, harmful, deceptive, or rights-infringing content.","Do not probe another tenant, attempt unauthorized access, or misuse support access.","Do not resell or reverse engineer the service except where expressly permitted by law or written agreement."]},
      {title:"4. Customer content and privacy",paragraphs:["The customer retains its rights in customer content and grants Cankonix the limited rights required to host, transmit, process, secure, back up, and provide the service. The customer is responsible for having a lawful basis and required notices for content and participant data it submits.","Our handling of personal data is described in the Privacy Policy and, for business customers, the Data Processing Addendum."]},
      {title:"5. Plans, trials, billing, and taxes",paragraphs:["Trials and plan limits are shown at signup or in Plan & usage. Paid charges, currency, billing cycle, renewal, cancellation date, and taxes will be shown before checkout. Payment processing remains inactive until a supported provider is configured.","Failure to pay may lead to restricted paid features or suspension after reasonable notice, subject to applicable law and written enterprise terms."]},
      {title:"6. Availability, changes, and beta features",paragraphs:["We work to operate Xspace securely and reliably but do not promise uninterrupted availability unless a separate signed service-level agreement applies. Maintenance, emergency work, internet conditions, devices, third-party networks, or events outside reasonable control may affect service.","Preview or beta features may change or be withdrawn and should not be used for workloads requiring a separately agreed service commitment."]},
      {title:"7. Suspension and termination",paragraphs:["We may restrict access to protect customers, the service, or third parties; respond to legal requirements; address material breach; or prevent harm. Where practicable, we will provide notice and an opportunity to cure.","Customers may cancel according to their plan. On termination, access ends and content is deleted or returned according to the applicable retention settings, legal holds, DPA, and written agreement."]},
      {title:"8. Warranties, liability, and indemnity",paragraphs:["To the extent permitted by law, the service is provided on an as-available basis. Neither party excludes liability that cannot lawfully be excluded. Any negotiated warranties, indemnities, and liability limits in an order form or enterprise agreement take precedence over this draft.","Before commercial release, legal counsel must approve the final warranty exclusions, liability cap, indemnity allocation, and consumer-law treatment for the target market."]},
      {title:"9. Governing law and contact",paragraphs:["These Terms are intended to be governed by the laws of the Republic of Indonesia, subject to the final contracting entity, venue, and dispute clause approved before commercial release.","Questions and legal notices may be sent to info@cankonix.com. The final version must include the contracting entity's registered name and address."]},
    ]
  },
  privacy: {
    title:"Privacy Policy", version:"2026-08-29", summary:"How Xspace collects, uses, shares, protects, and retains personal data.",
    sections:[
      {title:"1. Scope and our role",paragraphs:["This policy applies to Xspace websites, workspace accounts, meetings, collaboration features, and support interactions operated by Cankonix Technology.","For account, website, security, billing, and direct support data, Cankonix generally acts as a personal data controller. For customer content processed on a business customer's instructions, the customer generally acts as controller and Cankonix as processor. Roles may differ under applicable law and the actual facts."]},
      {title:"2. Data we process",bullets:["Identity and workspace data: name, email, username, role, profile image, organization, and account status.","Collaboration data: meeting participation, messages, reactions, files, rooms, calendar events, recordings, and related metadata.","Device, security, and usage data: IP address, user agent, session/device details, authentication events, audit records, diagnostics, timestamps, and service metrics.","Commercial and support data: plan, entitlement, invoice and payment-provider references, support communications, and incident records. Xspace does not intentionally store full payment-card details."]},
      {title:"3. Purposes and lawful grounds",bullets:["Provide, secure, administer, support, and improve the service; authenticate users; prevent abuse; and maintain tenant isolation.","Perform a contract or take requested pre-contract steps; comply with law; protect legitimate security and operational interests; and process consent where consent is the appropriate legal basis.","Generate recordings only when initiated by an authorized host and subject to workspace policy, visible indication, participant notice, and applicable law."]},
      {title:"4. Sources and sharing",paragraphs:["We receive data from users, workspace administrators, invited guests, connected identity providers, devices, and configured service providers. We disclose data only as needed to operate the service, follow customer instructions, complete configured billing, meet legal duties, protect rights and safety, or complete an approved corporate transaction."],bullets:["Infrastructure, storage, realtime media, email delivery, observability, and configured payment providers may process limited data for their service function.","Workspace administrators can access tenant data according to their permissions and policies.","We do not sell personal data or use customer content for third-party advertising."]},
      {title:"5. Retention and deletion",paragraphs:["Retention depends on data type, workspace policy, contract, security needs, and law. Customers can configure certain recording, message, file, and governance periods. Legal holds may pause deletion. Backups expire according to the backup lifecycle rather than immediate deletion.","Account and audit data may be retained as needed for security, dispute handling, compliance, and financial records. Data is deleted or de-identified when no longer required, subject to technical and legal limitations."]},
      {title:"6. Security and international processing",paragraphs:["Xspace uses tenant scoping, role-based access, MFA, signed secure sessions, encryption in transit, private object storage, audit trails, retention controls, monitoring, backups, and incident procedures. No system is risk-free.","If data is processed outside Indonesia or transferred across borders, we will use the notices, safeguards, contractual measures, and assessments required by applicable law and the customer agreement."]},
      {title:"7. Your choices and rights",paragraphs:["Subject to applicable law, individuals may request information, access, correction, completion, deletion, restriction, objection, withdrawal of consent, or other available rights. Requests should be sent to info@cankonix.com and may require identity and workspace verification.","Some requests must be handled by the workspace customer as controller. We will support verified customer instructions under the DPA. Withdrawing consent does not affect processing already lawfully completed."]},
      {title:"8. Children, changes, and contact",paragraphs:["Xspace is a business collaboration service and is not directed to children. A customer that permits minors must establish an appropriate lawful basis, notices, permissions, and safeguards.","Material policy changes will be dated and communicated through appropriate service or account notices. Privacy questions and requests: info@cankonix.com. The final policy must include the approved controller identity and registered address."]},
    ]
  },
  dpa: {
    title:"Data Processing Addendum", version:"2026-08-29", summary:"Draft processor terms for business customers using Xspace.",
    sections:[
      {title:"1. Parties, scope, and order of precedence",paragraphs:["This DPA supplements the agreement between the Xspace customer (Customer) and the approved Cankonix contracting entity (Processor). It applies when Processor handles personal data on Customer's documented instructions to provide Xspace.","The signed order form and negotiated DPA control over this online draft where they conflict. Customer is controller and Cankonix is processor unless applicable law assigns different roles."]},
      {title:"2. Processing instructions and compliance",bullets:["Process personal data only to provide, secure, support, maintain, and delete or return Xspace data under the agreement and documented Customer instructions.","Inform Customer if an instruction appears unlawful, unless prohibited from doing so.","Ensure personnel with access are bound by confidentiality and receive appropriate security and privacy obligations.","Customer is responsible for lawful instructions, notices, legal bases, participant permissions, and data accuracy."]},
      {title:"3. Security measures",bullets:["Tenant-scoped authorization, least-privilege roles, administrative audit trails, MFA and enterprise identity controls.","TLS in transit, protected credentials and secrets, private object storage, backup and recovery controls.","Monitoring, vulnerability review, incident response, retention, legal hold, export, and controlled deletion workflows.","Regular review of technical and organizational measures appropriate to risk and service evolution."]},
      {title:"4. Subprocessors",paragraphs:["Customer authorizes subprocessors needed for infrastructure, email, realtime communication, storage, observability, support, and configured payments, subject to written data-protection obligations. Before commercial sign-off, Cankonix must publish the current subprocessor list, processing location, and change-notification mechanism.","Cankonix remains responsible for subprocessor obligations to the extent required by the final agreement and applicable law."]},
      {title:"5. Data subject requests and government demands",paragraphs:["Taking into account the nature of processing, Cankonix will reasonably assist Customer with verified rights requests, regulatory inquiries, and required impact assessments. Cankonix will not independently respond on Customer's behalf unless required by law or authorized.","Cankonix will notify Customer of legally binding demands for Customer data when permitted and will disclose only what is legally required."]},
      {title:"6. Personal data breach",paragraphs:["Cankonix will notify Customer without undue delay after confirming a personal data breach affecting Customer data and will provide available information reasonably needed for Customer's duties. Notification is not an admission of fault.","The final DPA must specify the agreed notification channel, contacts, and any contractual timing aligned with Indonesian law and target markets."]},
      {title:"7. Return, deletion, audit, and transfer",paragraphs:["At termination or on valid instruction, Cankonix will return or delete Customer data according to service capabilities, retention schedules, legal holds, backups, and law. Cankonix will provide reasonable compliance information and support proportionate audits under confidentiality and security controls.","Cross-border processing will use required safeguards. Details of hosting region, subprocessors, deletion periods, and transfer mechanisms must be completed in the signed annexes."]},
      {title:"Annex — processing description",bullets:["Subject matter: secure business collaboration and administration.","Duration: subscription term plus configured retention, backup expiry, dispute, and legal-hold periods.","People: workspace users, invited participants, guests, administrators, support contacts, and individuals appearing in customer content.","Data: identity, contact, profile, participation, communications, files, recordings, calendar, security, device, usage, audit, support, and limited billing references.","Sensitive data: not required for ordinary use; Customer must avoid unnecessary sensitive content and apply heightened controls where processing is lawful and necessary."]},
    ]
  },
  cookies: {
    title:"Cookie Notice", version:"2026-08-29", summary:"The essential browser storage Xspace uses and the controls available to you.",
    sections:[
      {title:"1. Current use",paragraphs:["Xspace currently uses an essential HttpOnly session cookie to keep authenticated users signed in securely. The cookie is scoped to the service, uses SameSite protection, and is marked Secure in production.","Xspace also uses browser local storage to remember the selected light or dark-green theme. Theme storage does not identify you across unrelated websites."]},
      {title:"2. No advertising cookies",paragraphs:["As of this version, Xspace does not use third-party advertising cookies or cross-site behavioral tracking. Operational logs and service metrics are generated server-side for security, reliability, and diagnostics."]},
      {title:"3. Controls and future changes",paragraphs:["Blocking the essential session cookie prevents authenticated workspace features from working. You can clear cookies and local storage through browser settings, which signs you out and resets preferences.","If optional analytics or other non-essential browser tracking is introduced, Xspace will update this notice and provide any consent control required by applicable law before activation."]},
    ]
  },
  recording: {
    title:"Meeting Recording Notice", version:"2026-08-29", summary:"Responsibilities and participant choices when an Xspace meeting is recorded.",
    sections:[
      {title:"1. Visible, authorized recording",paragraphs:["Only an authorized meeting host may start or stop an Xspace recording. The live meeting displays a recording state when recording is active. Hosts and customers must not conceal recording or use Xspace for unauthorized surveillance."]},
      {title:"2. Host and customer responsibilities",bullets:["Give participants clear notice before recording starts and explain the purpose, expected use, access, sharing, and retention.","Establish an appropriate lawful basis and obtain consent where consent is required. Additional rules may apply to employees, confidential discussions, minors, health, biometric, or other sensitive data.","Provide a reasonable alternative for a person who cannot or does not wish to be recorded, such as joining before recording, leaving, or using a non-recorded channel.","Restrict recording access, configure retention, honor valid rights requests, and prevent unauthorized download or redistribution."]},
      {title:"3. Participant acknowledgement and choices",paragraphs:["The prejoin screen requires participants to acknowledge that the host may record and that Xspace will show a visible recording indicator. Joining does not remove any right to ask questions, object, withdraw consent where applicable, or leave before or during recording.","If recording starts unexpectedly or the stated purpose changes, participants should ask the host to stop and may leave the meeting. Contact the workspace administrator for access, correction, deletion, restriction, or complaint requests relating to a recording."]},
      {title:"4. Storage, access, and retention",paragraphs:["Recordings are stored in private tenant-scoped storage and are available only to authorized users. Workspace retention policy, deletion actions, legal holds, backup expiry, and applicable law determine how long recordings remain.","Cankonix processes recordings for the customer under the Privacy Policy and DPA. Xspace does not use recording content for advertising."]},
    ]
  }
};
