"use client";

import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import styles from "./calendar.module.css";

type CalendarEvent = { id:string; title:string; description:string; timezone:string; startsAt:string; endsAt:string; recurrenceRule?:string; reminderMinutes:number; organizerId:string; organizerName:string; attendeeStatus:string; attendeeCount:number; meetingJoinCode?:string; meetingStatus?:string; participantCount:number };

export default function CalendarPage(){
  const [events,setEvents]=useState<CalendarEvent[]>([]),[error,setError]=useState(""),[saving,setSaving]=useState(false);
  const [title,setTitle]=useState(""),[startsAt,setStartsAt]=useState(""),[endsAt,setEndsAt]=useState(""),[recurrence,setRecurrence]=useState(""),[createMeeting,setCreateMeeting]=useState(true);
  useEffect(()=>{let active=true;void fetch("/api/v1/calendar/events").then(async response=>{const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data?.error?.message??"Could not load calendar");if(active)setEvents(data.events??[])}).catch(reason=>{if(active)setError(reason instanceof Error?reason.message:"Could not load calendar")});return()=>{active=false}},[]);
  async function create(event:FormEvent){event.preventDefault();setSaving(true);setError("");const timezone=Intl.DateTimeFormat().resolvedOptions().timeZone||"Asia/Jakarta";const response=await fetch("/api/v1/calendar/events",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({title,description:"",timezone,startsAt:new Date(startsAt).toISOString(),endsAt:new Date(endsAt).toISOString(),recurrenceRule:recurrence,reminderMinutes:15,attendeeIds:[],createMeeting})});const data=await response.json().catch(()=>({}));setSaving(false);if(!response.ok){setError(data?.error?.message??"Could not create event");return}setTitle("");setStartsAt("");setEndsAt("");setEvents(items=>[...items,data.event].sort((a,b)=>a.startsAt.localeCompare(b.startsAt)))}
  async function respond(id:string,status:"ACCEPTED"|"DECLINED"){const response=await fetch(`/api/v1/calendar/events/${id}/response`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({status})});if(response.ok)setEvents(items=>items.map(item=>item.id===id?{...item,attendeeStatus:status}:item));else setError("Could not update invitation")}
  return <main className={styles.page}><header><div><p>XSPACE PLANNING</p><h1>Calendar</h1><span>Events, reminders, invitations, and linked meetings.</span></div><Link href="/">← Workspace</Link></header>{error&&<p className={styles.error} role="alert">{error}</p>}<section className={styles.layout}><form className={styles.form} onSubmit={create}><h2>Create event</h2><label>Title<input value={title} onChange={e=>setTitle(e.target.value)} minLength={3} maxLength={160} required/></label><label>Starts<input type="datetime-local" value={startsAt} onChange={e=>setStartsAt(e.target.value)} required/></label><label>Ends<input type="datetime-local" value={endsAt} onChange={e=>setEndsAt(e.target.value)} required/></label><label>Repeat<select value={recurrence} onChange={e=>setRecurrence(e.target.value)}><option value="">Does not repeat</option><option value="DAILY">Daily</option><option value="WEEKLY">Weekly</option><option value="MONTHLY">Monthly</option></select></label><label className={styles.check}><input type="checkbox" checked={createMeeting} onChange={e=>setCreateMeeting(e.target.checked)}/> Create secure Xspace meeting</label><button disabled={saving}>{saving?"Creating…":"Create event"}</button></form><section className={styles.events}><div className={styles.eventsHead}><h2>Schedule</h2><span>{events.length} events</span></div>{events.length===0?<p className={styles.empty}>No calendar events yet.</p>:events.map(item=><article key={item.id}><time><strong>{new Intl.DateTimeFormat("en",{day:"2-digit"}).format(new Date(item.startsAt))}</strong><span>{new Intl.DateTimeFormat("en",{month:"short"}).format(new Date(item.startsAt))}</span></time><div><h3>{item.title}</h3><p>{new Intl.DateTimeFormat("en",{dateStyle:"medium",timeStyle:"short",timeZone:item.timezone}).format(new Date(item.startsAt))} · {item.timezone}</p><small>{item.organizerName} · {item.attendeeCount} attendees{item.recurrenceRule?` · ${item.recurrenceRule.toLowerCase()}`:""}</small>{item.meetingJoinCode&&<Link className={styles.join} href={`/meet/${item.meetingJoinCode}/prejoin`}>Join meeting · {item.meetingJoinCode}</Link>}{item.attendeeStatus==="INVITED"&&<div className={styles.actions}><button onClick={()=>void respond(item.id,"ACCEPTED")}>Accept</button><button onClick={()=>void respond(item.id,"DECLINED")}>Decline</button></div>}</div></article>)}</section></section></main>}
