"use client";

import { FormEvent, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import Image from "next/image";
import sidebarLogo from "../asset/Logo-transparent.png";
import thumbnailLogo from "../asset/Logo-Thumbnail-transparent.png";

type IconName = "grid" | "video" | "calendar" | "users" | "record" | "chart" | "settings" | "search" | "bell" | "plus" | "link" | "clock" | "arrow" | "play" | "spark" | "menu" | "close" | "check" | "shield" | "more";
type Meeting = { title: string; time: string; people: string; starts: string; accent: string };
type Modal = "new" | "join" | "schedule" | null;
type SessionUser = { displayName: string; email: string; tenantName: string; role: string };

const meetings: Meeting[] = [
  { title: "Product Roadmap Discussion", time: "09:00 – 10:30", people: "6 participants", starts: "Starts in 18 min", accent: "#f7c86b" },
  { title: "Project X Weekly Sync", time: "11:00 – 12:00", people: "8 participants", starts: "Starts in 2 hours", accent: "#a3e635" },
  { title: "Executive Briefing", time: "14:00 – 15:00", people: "14 participants", starts: "Starts in 5 hours", accent: "#8ba8ff" },
  { title: "Technical Workshop", time: "16:00 – 17:30", people: "15 participants", starts: "Tomorrow", accent: "#c59cff" },
];
const recordings = [
  { title: "Project X Weekly Sync", detail: "May 12, 2026", duration: "42:18", color: "#a3e635" },
  { title: "Product Roadmap Discussion", detail: "May 11, 2026", duration: "55:25", color: "#f7c86b" },
  { title: "Executive Briefing", detail: "May 10, 2026", duration: "58:47", color: "#8ba8ff" },
];
const navigation: [IconName, string][] = [["grid", "Overview"], ["video", "Meetings"], ["calendar", "Calendar"], ["users", "People"], ["record", "Recordings"], ["chart", "Analytics"], ["settings", "Settings"]];

function Icon({ name, size = 18 }: { name: IconName; size?: number }) {
  const paths: Record<IconName, React.ReactNode> = {
    grid: <><rect x="3" y="3" width="7" height="7" rx="2"/><rect x="14" y="3" width="7" height="7" rx="2"/><rect x="3" y="14" width="7" height="7" rx="2"/><rect x="14" y="14" width="7" height="7" rx="2"/></>,
    video: <><rect x="3" y="6" width="13" height="12" rx="3"/><path d="m16 10 5-3v10l-5-3"/></>, calendar: <><rect x="3" y="5" width="18" height="16" rx="3"/><path d="M8 3v4m8-4v4M3 10h18"/></>,
    users: <><path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M22 21v-2a4 4 0 0 0-3-3.87M16 3.13a4 4 0 0 1 0 7.75"/></>,
    record: <><rect x="3" y="4" width="18" height="16" rx="3"/><circle cx="12" cy="12" r="3"/></>, chart: <path d="M4 19V9m6 10V5m6 14v-7m6 7H2"/>, settings: <><circle cx="12" cy="12" r="3"/><path d="M19 15a2 2 0 0 0 .4 2l-2.4 2.4a2 2 0 0 0-2-.4 2 2 0 0 0-1 2h-4a2 2 0 0 0-1-2 2 2 0 0 0-2 .4L4.6 17A2 2 0 0 0 5 15a2 2 0 0 0-2-1v-4a2 2 0 0 0 2-1 2 2 0 0 0-.4-2L7 4.6A2 2 0 0 0 9 5a2 2 0 0 0 1-2h4a2 2 0 0 0 1 2 2 2 0 0 0 2-.4L19.4 7A2 2 0 0 0 19 9a2 2 0 0 0 2 1v4a2 2 0 0 0-2 1Z"/></>,
    search: <><circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/></>, bell: <><path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9M10 21h4"/></>, plus: <path d="M12 5v14M5 12h14"/>, link: <><path d="M10 13a5 5 0 0 0 7 .1l2-2A5 5 0 0 0 12 4l-1 1"/><path d="M14 11a5 5 0 0 0-7-.1l-2 2A5 5 0 0 0 12 20l1-1"/></>, clock: <><circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/></>, arrow: <path d="m9 18 6-6-6-6"/>, play: <path d="m9 7 8 5-8 5Z"/>, spark: <path d="m12 3 1.4 4.2L18 9l-4.6 1.8L12 15l-1.4-4.2L6 9l4.6-1.8L12 3Zm6 12 .7 2.3L21 18l-2.3.7L18 21l-.7-2.3L15 18l2.3-.7L18 15Z"/>, menu: <path d="M4 7h16M4 12h16M4 17h16"/>, close: <path d="m6 6 12 12M18 6 6 18"/>, check: <path d="m5 12 4 4L19 6"/>, shield: <path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10Z"/>, more: <><circle cx="5" cy="12" r="1" fill="currentColor"/><circle cx="12" cy="12" r="1" fill="currentColor"/><circle cx="19" cy="12" r="1" fill="currentColor"/></>,
  };
  return <svg aria-hidden="true" width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">{paths[name]}</svg>;
}
function Brand({collapsed=false}:{collapsed?:boolean}) { return <div className="brand"><Image src={collapsed?thumbnailLogo:sidebarLogo} alt="Xpace" priority sizes={collapsed?"48px":"190px"}/></div>; }

export default function Home() {
  const router = useRouter();
  const [modal, setModal] = useState<Modal>(null); const [mobileOpen, setMobileOpen] = useState(false); const [collapsed,setCollapsed]=useState(false); const [toast, setToast] = useState<string | null>(null); const [active, setActive] = useState("Overview");
  const [sessionUser, setSessionUser] = useState<SessionUser | null>(null);
  useEffect(() => { let active = true; void fetch("/api/v1/auth/me").then(async response => { if (response.status === 401) { router.replace("/login"); return; } const data = await response.json(); if (active && response.ok) setSessionUser(data.user); }).catch(() => undefined); return () => { active = false; }; }, [router]);
  useEffect(() => { if (!toast) return; const timer = window.setTimeout(() => setToast(null), 3600); return () => window.clearTimeout(timer); }, [toast]);
  useEffect(() => {
    const media = window.matchMedia("(max-width: 760px)");
    const expandForMobile = () => { if (media.matches) setCollapsed(false); };
    expandForMobile();
    media.addEventListener("change", expandForMobile);
    return () => media.removeEventListener("change", expandForMobile);
  }, []);
  const notify = (message: string) => setToast(message);
  const navTo = (label: string) => { setActive(label); setMobileOpen(false); if (label === "Analytics") { router.push("/admin"); return; } if (label !== "Overview") notify(`${label} is ready for the next product module.`); };
  const submit = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault(); const form = new FormData(event.currentTarget);
    const joining = modal === "join"; const code = String(form.get("code") ?? "").trim().toUpperCase(); const endpoint = joining ? `/api/v1/meetings/${encodeURIComponent(code)}` : "/api/v1/meetings";
    const body = joining ? {} : { title: form.get("title"), scheduledAt: modal === "schedule" ? new Date(`${form.get("date")}T${form.get("time")}`).toISOString() : null, waitingRoomEnabled: form.get("waiting") === "on" };
    try { const response = await fetch(endpoint,{method:joining?"GET":"POST",headers:{"Content-Type":"application/json"},...(joining?{}:{body:JSON.stringify(body)})}); const result = await response.json().catch(()=>({})); if(!response.ok) throw new Error(result?.error?.message ?? "Request failed"); setModal(null); if(joining || modal === "new") router.push(`/meet/${encodeURIComponent(result.meeting.joinCode)}/prejoin`); else notify(`Meeting scheduled · ${result.meeting.joinCode}`); }
    catch(error){ notify(error instanceof Error ? error.message : "Could not connect to Xpace API"); }
  };
  return <div className={`app-shell ${collapsed?"sidebar-collapsed":""} ${mobileOpen?"mobile-nav-open":""}`}>
    <aside className={`sidebar ${mobileOpen ? "sidebar-open" : ""}`}><div className="sidebar-head"><Brand collapsed={collapsed}/><button className="collapse-button" aria-label={collapsed?"Expand sidebar":"Collapse sidebar"} onClick={()=>setCollapsed(!collapsed)}><Icon name="arrow"/></button></div><nav aria-label="Main navigation"><p>WORKSPACE</p>{navigation.slice(0,5).map(([icon,label])=><button title={collapsed?label:undefined} key={label} onClick={()=>navTo(label)} className={active===label?"active":""}><Icon name={icon}/><span>{label}</span>{label==="Meetings"&&<small>3</small>}</button>)}<p>MANAGE</p>{navigation.slice(5).map(([icon,label])=><button title={collapsed?label:undefined} key={label} onClick={()=>navTo(label)} className={active===label?"active":""}><Icon name={icon}/><span>{label}</span></button>)}</nav><div className="upgrade"><Icon name="spark"/><strong>Unlock more with Pro</strong><p>Advanced analytics, AI notes, and unlimited recording.</p><button onClick={()=>notify("A tailored Pro plan is ready for your team.")}>Explore Pro</button></div><div className="profile"><span>{initials(sessionUser?.displayName)}<i/></span><div><strong>{sessionUser?.displayName ?? "Loading profile…"}</strong><small>{sessionUser?.email ?? "Secure session"}</small></div><Icon name="more"/></div></aside>
    {mobileOpen&&<button aria-label="Close navigation overlay" className="scrim" onClick={()=>setMobileOpen(false)}/>}<main><header className="topbar"><button className="icon-button mobile-only" aria-label="Open navigation" onClick={()=>setMobileOpen(true)}><Icon name="menu"/></button><label className="search"><Icon name="search"/><input aria-label="Search workspace" placeholder="Search meetings, people, recordings..."/><kbd>⌘ K</kbd></label><div className="top-actions"><button className="icon-button notification" aria-label="Notifications" onClick={()=>notify("You're all caught up.")}><Icon name="bell"/><i aria-hidden="true"/></button><button className="help" aria-label="Open Xpace help" onClick={()=>notify("Xpace support is available 24/7.")}>?</button></div></header>
      <div className="content"><section className="welcome"><div><p className="eyebrow"><i/> {new Intl.DateTimeFormat("en",{weekday:"long",day:"2-digit",month:"long"}).format(new Date()).toUpperCase()}</p><h1>Good morning, {sessionUser?.displayName.split(" ")[0] ?? "there"} <span>👋</span></h1><p>Your workspace is running smoothly. Here&apos;s what needs your attention today.</p></div><div className="actions"><button className="secondary" onClick={()=>setModal("join")}><Icon name="link"/> Join with code</button><button className="primary" onClick={()=>setModal("new")}><Icon name="plus"/> New meeting</button></div></section>
      <section className="hero-grid"><article className="next"><div className="orb"/><div className="next-top"><span><i/> NEXT MEETING</span><Icon name="more"/></div><div className="next-body"><p>09:00 — 10:30</p><h2>Product Roadmap<br/>Discussion</h2><div><span><Icon name="clock" size={15}/> Starts in 18 minutes</span><span><Icon name="users" size={15}/> 6 participants</span></div></div><div className="next-foot"><div className="avatars"><span>AN</span><span>DK</span><span>MR</span><span>+3</span></div><button onClick={()=>notify("Opening secure pre-join preview...")}><Icon name="video"/> Join meeting <Icon name="arrow" size={16}/></button></div></article>
      <Quick icon="video" title="Start an instant meeting" text="Create a secure room and invite your team in seconds." button="Start now" onClick={()=>setModal("new")}/><Quick icon="calendar" title="Schedule for later" text="Plan ahead and send calendar invitations to everyone." button="Schedule" onClick={()=>setModal("schedule")}/></section>
      <section className="stats">{[["calendar","Upcoming","12","+3 this week","green"],["video","Live now","3","2 rooms active","orange"],["users","Participants","156","+18% this week","blue"],["record","Recorded","24.5h","+4.2h this week","purple"]].map(([icon,label,value,hint,tone])=><article key={label}><span className={tone}><Icon name={icon as IconName}/></span><div><p>{label}</p><strong>{value}</strong></div><small>{hint}</small></article>)}</section>
      <section className="lower"><article className="panel upcoming"><PanelHead title="Upcoming meetings" text="Your schedule for today and tomorrow" action="View calendar" onClick={()=>navTo("Meetings")}/><div className="meeting-list">{meetings.map((m,i)=><div className="meeting" key={m.title}><div className="date"><b>{i===3?"21":"20"}</b><small>AUG</small></div><i style={{background:m.accent}}/><div><strong>{m.title}</strong><p>{m.time} · {m.people}</p></div><span style={{color:m.accent}}>{m.starts}</span><button aria-label={`Open ${m.title}`} onClick={()=>notify(`${m.title} details opened.`)}><Icon name="arrow"/></button></div>)}</div></article>
      <article className="panel recordings"><PanelHead title="Recent recordings" text="Ready to watch and share" action="View all" onClick={()=>navTo("Recordings")}/><div className="record-list">{recordings.map(r=><button key={r.title} onClick={()=>notify(`Playing ${r.title}.`)}><span className="thumb" style={{"--record":r.color} as React.CSSProperties}><Icon name="play"/></span><span><strong>{r.title}</strong><small>{r.detail} · {r.duration}</small></span><Icon name="more"/></button>)}</div><div className="storage"><Icon name="shield"/><div><strong>Enterprise-grade security</strong><small>End-to-end encrypted recordings</small></div><i><b/></i></div></article></section><footer><span><i/> All systems operational</span><p>Securely connected · Jakarta region</p><small>© 2026 Cankonix Technology</small></footer></div></main>
    {modal&&<div className="backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setModal(null)}}><div className="modal" role="dialog" aria-modal="true" aria-labelledby="modal-title"><button className="modal-close" aria-label="Close" onClick={()=>setModal(null)}><Icon name="close"/></button><span className="modal-icon"><Icon name={modal==="schedule"?"calendar":modal==="join"?"link":"video"}/></span><p>XPACE SECURE MEET</p><h2 id="modal-title">{modal==="join"?"Join a meeting":modal==="schedule"?"Schedule a meeting":"Start a new meeting"}</h2><em>{modal==="join"?"Enter the meeting code shared by your host.":modal==="schedule"?"Choose when your team should come together.":"Your secure room will be ready in just one click."}</em><form onSubmit={submit}>{modal==="join"?<label>Meeting code<input name="code" autoFocus required placeholder="e.g. XPC-482-190" pattern="[A-Za-z0-9-]{6,}"/></label>:<><label>Meeting title<input name="title" autoFocus required defaultValue={modal==="new"?"Instant team sync":"Team collaboration session"}/></label>{modal==="schedule"&&<div className="field-row"><label>Date<input name="date" required type="date" defaultValue="2026-08-21"/></label><label>Time<input name="time" required type="time" defaultValue="10:00"/></label></div>}</>}<label className="toggle"><span><strong>Waiting room</strong><small>Review guests before they enter</small></span><input name="waiting" type="checkbox" defaultChecked/></label><button className="primary" type="submit">{modal==="join"?"Continue to preview":modal==="schedule"?"Schedule meeting":"Create secure room"}<Icon name="arrow"/></button></form></div></div>}
    {toast&&<div className="toast" role="status"><span><Icon name="check"/></span>{toast}<button aria-label="Dismiss" onClick={()=>setToast(null)}><Icon name="close"/></button></div>}
  </div>;
}
function Quick({icon,title,text,button,onClick}:{icon:IconName;title:string;text:string;button:string;onClick:()=>void}){return <article className="quick"><div><span><Icon name={icon}/></span><h3>{title}</h3><p>{text}</p></div><button onClick={onClick}>{button}<Icon name="arrow"/></button></article>}
function PanelHead({title,text,action,onClick}:{title:string;text:string;action:string;onClick:()=>void}){return <div className="panel-head"><div><h2>{title}</h2><p>{text}</p></div><button onClick={onClick}>{action}<Icon name="arrow"/></button></div>}
function initials(value?:string){const parts=(value??"XP").trim().split(/\s+/).filter(Boolean);return parts.slice(0,2).map(part=>part[0]?.toUpperCase()).join("")||"XP";}
