"use client";

import { useCallback, useEffect, useState } from "react";
import styles from "./platform.module.css";

type Overview={tenants:{total:number;active:number;suspended:number;trialing:number;pastDue:number};usage:{users:number;meetings30Days:number;storageBytes:number}};
type Tenant={id:string;slug:string;name:string;platformStatus:string;subscriptionStatus:string;planKey:string;ownerEmail:string;users:number;meetings30Days:number;storageBytes:number;trialEndsAt?:string;periodEndsAt?:string;suspendedAt?:string;suspensionReason?:string;createdAt:string};
type TenantDetail={tenant:Tenant;usage:{meetings:number;recordings:number;activeUsers:number;errors24Hours:number};supportAccess:{active:boolean;id:string;expiresAt?:string}};
type SupportUser={id:string;email:string;username:string;displayName:string;role:string;status:string;createdAt:string};
type ActionKind="suspend"|"reactivate"|"support";

export default function PlatformPage(){
  const [overview,setOverview]=useState<Overview|null>(null),[tenants,setTenants]=useState<Tenant[]>([]),[total,setTotal]=useState(0),[page,setPage]=useState(1),[search,setSearch]=useState(""),[query,setQuery]=useState(""),[status,setStatus]=useState(""),[loading,setLoading]=useState(true),[error,setError]=useState("");
  const [detail,setDetail]=useState<TenantDetail|null>(null),[detailLoading,setDetailLoading]=useState(false),[action,setAction]=useState<ActionKind|null>(null),[reason,setReason]=useState(""),[duration,setDuration]=useState(30),[busy,setBusy]=useState(false),[supportUsers,setSupportUsers]=useState<SupportUser[]>([]);
  const pageSize=20;
  const load=useCallback(async()=>{setLoading(true);setError("");try{const params=new URLSearchParams({page:String(page),pageSize:String(pageSize)});if(query)params.set("search",query);if(status)params.set("status",status);const [overviewResponse,tenantResponse]=await Promise.all([fetch("/api/v1/platform/overview"),fetch(`/api/v1/platform/tenants?${params}`)]);const [overviewData,tenantData]=await Promise.all([overviewResponse.json().catch(()=>({})),tenantResponse.json().catch(()=>({}))]);if(!overviewResponse.ok)throw new Error(overviewData?.error?.message??"Could not load platform overview");if(!tenantResponse.ok)throw new Error(tenantData?.error?.message??"Could not load workspaces");setOverview(overviewData);setTenants(tenantData.tenants??[]);setTotal(tenantData.total??0)}catch(value){setError(value instanceof Error?value.message:"Could not load SaaS administration")}finally{setLoading(false)}},[page,query,status]);
  useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer)},[load]);
  async function openDetail(tenant:Tenant){setDetailLoading(true);setSupportUsers([]);try{const response=await fetch(`/api/v1/platform/tenants/${tenant.id}`),data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data?.error?.message??"Could not load workspace details");setDetail(data)}catch(value){setError(value instanceof Error?value.message:"Could not load workspace details")}finally{setDetailLoading(false)}}
  async function refreshDetail(){if(!detail)return;await openDetail(detail.tenant)}
  function openAction(kind:ActionKind){setAction(kind);setReason("");setDuration(30)}
  async function submitAction(){if(!detail||!action)return;setBusy(true);setError("");try{const endpoint=action==="support"?`/api/v1/platform/tenants/${detail.tenant.id}/support-access`:`/api/v1/platform/tenants/${detail.tenant.id}/${action}`;const body=action==="support"?{reason,durationMinutes:duration}:{reason};const response=await fetch(endpoint,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}),data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data?.error?.message??"Workspace action failed");setAction(null);await load();await refreshDetail()}catch(value){setError(value instanceof Error?value.message:"Workspace action failed")}finally{setBusy(false)}}
  async function revokeSupport(){if(!detail)return;setBusy(true);try{const response=await fetch(`/api/v1/platform/tenants/${detail.tenant.id}/support-access`,{method:"DELETE"}),data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data?.error?.message??"Could not revoke support access");setSupportUsers([]);await refreshDetail()}catch(value){setError(value instanceof Error?value.message:"Could not revoke support access")}finally{setBusy(false)}}
  async function loadSupportView(){if(!detail)return;setBusy(true);try{const response=await fetch(`/api/v1/platform/tenants/${detail.tenant.id}/support-view`),data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data?.error?.message??"Could not load support view");setSupportUsers(data.users??[])}catch(value){setError(value instanceof Error?value.message:"Could not load support view")}finally{setBusy(false)}}
  const pages=Math.max(1,Math.ceil(total/pageSize));
  return <main className={styles.page}>
    <header className={styles.hero}><div><p>XSPACE PLATFORM</p><h1>SaaS administration</h1><span>Manage workspace lifecycle, usage, subscriptions, and controlled support access.</span></div><button onClick={()=>void load()} disabled={loading}>Refresh data</button></header>
    {error&&<div className={styles.error} role="alert"><span>{error}</span><button aria-label="Dismiss error" onClick={()=>setError("")}>×</button></div>}
    <section className={styles.metrics} aria-label="Platform overview">
      <Metric label="Workspaces" value={overview?.tenants.total} detail={`${overview?.tenants.active??0} active · ${overview?.tenants.suspended??0} suspended`}/>
      <Metric label="Trial workspaces" value={overview?.tenants.trialing} detail={`${overview?.tenants.pastDue??0} past due`}/>
      <Metric label="Platform users" value={overview?.usage.users} detail="Non-deactivated identities"/>
      <Metric label="Meetings (30 days)" value={overview?.usage.meetings30Days} detail={formatBytes(overview?.usage.storageBytes??0)+" stored"}/>
    </section>
    <section className={styles.panel}>
      <div className={styles.filters}><form onSubmit={event=>{event.preventDefault();setPage(1);setQuery(search.trim())}}><label><span className="sr-only">Search workspaces</span><input value={search} onChange={event=>setSearch(event.target.value)} placeholder="Search workspace name or URL…"/><button>Search</button></label></form><select aria-label="Filter workspace status" value={status} onChange={event=>{setStatus(event.target.value);setPage(1)}}><option value="">All statuses</option><option value="ACTIVE">Active</option><option value="SUSPENDED">Suspended</option></select></div>
      <div className={styles.tableWrap}><div className={styles.tableHead}><span>Workspace</span><span>Plan</span><span>Users</span><span>Meetings 30d</span><span>Storage</span><span>Status</span><span/></div>{loading?<p className={styles.empty}>Loading platform workspaces…</p>:tenants.length===0?<p className={styles.empty}>No workspaces match this filter.</p>:tenants.map(tenant=><article className={styles.row} key={tenant.id}><div><strong>{tenant.name}</strong><small>{tenant.slug} · {tenant.ownerEmail||"No owner email"}</small></div><div><b>{tenant.planKey}</b><small>{formatStatus(tenant.subscriptionStatus)}</small></div><span>{tenant.users.toLocaleString()}</span><span>{tenant.meetings30Days.toLocaleString()}</span><span>{formatBytes(tenant.storageBytes)}</span><Status value={tenant.platformStatus}/><button onClick={()=>void openDetail(tenant)}>View details</button></article>)}</div>
      <footer className={styles.pagination}><span>Showing {tenants.length} of {total} workspaces</span><div><button disabled={page<=1} onClick={()=>setPage(value=>value-1)}>Previous</button><b>{page} / {pages}</b><button disabled={page>=pages} onClick={()=>setPage(value=>value+1)}>Next</button></div></footer>
    </section>
    {(detail||detailLoading)&&<><button className={styles.scrim} aria-label="Close workspace details" onClick={()=>setDetail(null)}/><aside className={styles.drawer}>{detailLoading&&!detail?<p className={styles.empty}>Loading details…</p>:detail&&<><header><div><p>WORKSPACE DETAIL</p><h2>{detail.tenant.name}</h2><span>{detail.tenant.slug} · Created {formatDate(detail.tenant.createdAt)}</span></div><button aria-label="Close workspace details" onClick={()=>setDetail(null)}>×</button></header><div className={styles.detailStatus}><Status value={detail.tenant.platformStatus}/><span>{detail.tenant.planKey} · {formatStatus(detail.tenant.subscriptionStatus)}</span></div><dl className={styles.detailGrid}><div><dt>Owner</dt><dd>{detail.tenant.ownerEmail||"—"}</dd></div><div><dt>Active users</dt><dd>{detail.usage.activeUsers}</dd></div><div><dt>Total meetings</dt><dd>{detail.usage.meetings}</dd></div><div><dt>Recordings</dt><dd>{detail.usage.recordings}</dd></div><div><dt>Storage</dt><dd>{formatBytes(detail.tenant.storageBytes)}</dd></div><div><dt>Errors (24h)</dt><dd>{detail.usage.errors24Hours}</dd></div></dl>{detail.tenant.suspensionReason&&<div className={styles.notice}><strong>Suspension reason</strong><p>{detail.tenant.suspensionReason}</p></div>}<section className={styles.actions}><h3>Workspace lifecycle</h3>{detail.tenant.platformStatus==="ACTIVE"?<button className={styles.danger} onClick={()=>openAction("suspend")}>Suspend workspace</button>:<button className={styles.primary} onClick={()=>openAction("reactivate")}>Reactivate workspace</button>}</section><section className={styles.actions}><h3>Controlled support access</h3><p>Read-only directory access. Every start, view, and revoke action is audited.</p>{detail.supportAccess.active?<div className={styles.supportActive}><span>Active until {detail.supportAccess.expiresAt?formatDate(detail.supportAccess.expiresAt):"expiry"}</span><button onClick={()=>void loadSupportView()} disabled={busy}>Open support view</button><button onClick={()=>void revokeSupport()} disabled={busy}>Revoke</button></div>:<button onClick={()=>openAction("support")} disabled={detail.tenant.platformStatus!=="ACTIVE"}>Start support access</button>}</section>{supportUsers.length>0&&<section className={styles.supportUsers}><h3>Workspace directory</h3>{supportUsers.map(user=><div key={user.id}><span className={styles.avatar}>{initials(user.displayName)}</span><p><strong>{user.displayName}</strong><small>{user.email} · @{user.username}</small></p><b>{formatStatus(user.role)}</b><Status value={user.status}/></div>)}</section>}</>}</aside></>}
    {action&&detail&&<><button className={styles.modalScrim} aria-label="Cancel action" onClick={()=>setAction(null)}/><section className={styles.modal} role="dialog" aria-modal="true" aria-labelledby="platform-action-title"><h2 id="platform-action-title">{actionTitle(action)}</h2><p>{actionDescription(action,detail.tenant.name)}</p><label>Reason<textarea autoFocus value={reason} maxLength={500} onChange={event=>setReason(event.target.value)} placeholder="Provide an auditable business or support reason…"/></label>{action==="support"&&<label>Duration<select value={duration} onChange={event=>setDuration(Number(event.target.value))}><option value={15}>15 minutes</option><option value={30}>30 minutes</option><option value={60}>60 minutes</option><option value={120}>120 minutes</option></select></label>}<footer><button onClick={()=>setAction(null)}>Cancel</button><button className={action==="suspend"?styles.danger:styles.primary} disabled={busy||reason.trim().length<5} onClick={()=>void submitAction()}>{busy?"Working…":"Confirm action"}</button></footer></section></>}
  </main>
}

function Metric({label,value,detail}:{label:string;value?:number;detail:string}){return <article><span>{label}</span><strong>{value==null?"—":value.toLocaleString()}</strong><small>{detail}</small></article>}
function Status({value}:{value:string}){return <span className={`${styles.status} ${styles[value.toLowerCase()]??""}`}><i/>{formatStatus(value)}</span>}
function formatStatus(value:string){return value.toLowerCase().split("_").map(word=>word[0]?.toUpperCase()+word.slice(1)).join(" ")}
function formatBytes(value:number){if(value<1024)return `${value} B`;if(value<1024**2)return `${(value/1024).toFixed(1)} KB`;if(value<1024**3)return `${(value/1024**2).toFixed(1)} MB`;return `${(value/1024**3).toFixed(1)} GB`}
function formatDate(value:string){return new Intl.DateTimeFormat("en",{dateStyle:"medium",timeStyle:"short"}).format(new Date(value))}
function initials(value:string){return value.split(/\s+/).filter(Boolean).slice(0,2).map(part=>part[0]?.toUpperCase()).join("")||"XS"}
function actionTitle(action:ActionKind){return action==="suspend"?"Suspend workspace":action==="reactivate"?"Reactivate workspace":"Start support access"}
function actionDescription(action:ActionKind,name:string){if(action==="suspend")return `All active sessions in ${name} will be revoked immediately. Billing records remain unchanged.`;if(action==="reactivate")return `${name} users will be allowed to sign in again. Existing sessions are not restored.`;return `Grant temporary read-only directory access to ${name}. This does not impersonate a workspace user.`}
