"use client";

import Link from "next/link";
import { FormEvent, useCallback, useEffect, useState } from "react";
import styles from "./governance.module.css";
import exportStyles from "./exports.module.css";

type Policy = { recordingRetentionDays:number; driveTrashRetentionDays:number; chatRetentionDays:number; auditRetentionDays:number; updatedAt:string };
type HeldResource = { type:string; resourceId:string; addedAt:string };
type LegalHold = { id:string; name:string; reason:string; status:string; createdAt:string; releasedAt?:string; resources:HeldResource[] };
type RunResult = { chatMessages:number; chatAttachments:number; recordings:number; recordingObjects:number; driveFiles:number; auditEvents:number };
type DataExport = { id:string; exportType:string; reason:string; status:string; requestedByName:string; reviewedByName?:string; reviewNote?:string; sizeBytes?:number; sha256?:string; expiresAt?:string; downloadedAt?:string; createdAt:string; canReview:boolean };

export default function GovernancePage(){
  const[policy,setPolicy]=useState<Policy|null>(null),[holds,setHolds]=useState<LegalHold[]>([]),[exports,setExports]=useState<DataExport[]>([]),[message,setMessage]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false),[result,setResult]=useState<RunResult|null>(null);
  const[name,setName]=useState(""),[reason,setReason]=useState(""),[holdId,setHoldId]=useState(""),[resourceType,setResourceType]=useState("RECORDING"),[resourceId,setResourceId]=useState("");
  const[exportType,setExportType]=useState("FULL"),[exportReason,setExportReason]=useState("");
  const load=useCallback(async()=>{const[policyResponse,holdsResponse,exportsResponse]=await Promise.all([fetch("/api/v1/admin/governance/policy"),fetch("/api/v1/admin/governance/holds"),fetch("/api/v1/admin/governance/exports")]);const policyData=await policyResponse.json().catch(()=>({})),holdsData=await holdsResponse.json().catch(()=>({})),exportsData=await exportsResponse.json().catch(()=>({}));if(!policyResponse.ok)throw new Error(policyData?.error?.message??"Could not load retention policy");if(!holdsResponse.ok)throw new Error(holdsData?.error?.message??"Could not load legal holds");if(!exportsResponse.ok)throw new Error(exportsData?.error?.message??"Could not load data exports");setPolicy(policyData.policy);setHolds(holdsData.holds??[]);setExports(exportsData.exports??[])},[]);
  useEffect(()=>{let active=true;void Promise.all([fetch("/api/v1/admin/governance/policy"),fetch("/api/v1/admin/governance/holds"),fetch("/api/v1/admin/governance/exports")]).then(async([policyResponse,holdsResponse,exportsResponse])=>{const policyData=await policyResponse.json().catch(()=>({})),holdsData=await holdsResponse.json().catch(()=>({})),exportsData=await exportsResponse.json().catch(()=>({}));if(!policyResponse.ok)throw new Error(policyData?.error?.message??"Could not load retention policy");if(!holdsResponse.ok)throw new Error(holdsData?.error?.message??"Could not load legal holds");if(!exportsResponse.ok)throw new Error(exportsData?.error?.message??"Could not load data exports");if(active){setPolicy(policyData.policy);setHolds(holdsData.holds??[]);setExports(exportsData.exports??[])}}).catch(reason=>{if(active)setError(reason instanceof Error?reason.message:"Could not load governance settings")});return()=>{active=false}},[]);
  async function savePolicy(event:FormEvent){event.preventDefault();if(!policy)return;setBusy(true);setError("");const response=await fetch("/api/v1/admin/governance/policy",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(policy)}),data=await response.json().catch(()=>({}));setBusy(false);if(!response.ok){setError(data?.error?.message??"Could not save retention policy");return}setPolicy(data.policy);setMessage("Retention policy saved.")}
  async function createHold(event:FormEvent){event.preventDefault();setBusy(true);setError("");const response=await fetch("/api/v1/admin/governance/holds",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name,reason})}),data=await response.json().catch(()=>({}));setBusy(false);if(!response.ok){setError(data?.error?.message??"Could not create legal hold");return}setName("");setReason("");setMessage("Legal hold activated.");await load()}
  async function releaseHold(id:string){if(!window.confirm("Release this legal hold? Retention may process its resources on the next run."))return;setBusy(true);const response=await fetch(`/api/v1/admin/governance/holds/${id}/release`,{method:"POST"});setBusy(false);if(!response.ok){const data=await response.json().catch(()=>({}));setError(data?.error?.message??"Could not release legal hold");return}setMessage("Legal hold released.");await load()}
  async function addResource(event:FormEvent){event.preventDefault();setBusy(true);setError("");const response=await fetch(`/api/v1/admin/governance/holds/${holdId}/resources/${resourceType}/${resourceId.trim()}`,{method:"PUT"});setBusy(false);if(!response.ok){const data=await response.json().catch(()=>({}));setError(data?.error?.message??"Could not add resource to legal hold");return}setResourceId("");setMessage("Resource protected by legal hold.");await load()}
  async function removeResource(hold:string,resource:HeldResource){if(!window.confirm("Remove this resource from the legal hold?"))return;setBusy(true);const response=await fetch(`/api/v1/admin/governance/holds/${hold}/resources/${resource.type}/${resource.resourceId}`,{method:"DELETE"});setBusy(false);if(!response.ok){setError("Could not remove held resource");return}setMessage("Resource removed from legal hold.");await load()}
  async function runRetention(){if(!window.confirm("Run retention now? Expired chat and audit data will be removed, expired recordings hidden, and eligible Drive trash permanently deleted."))return;setBusy(true);setError("");const response=await fetch("/api/v1/admin/governance/retention/run",{method:"POST"}),data=await response.json().catch(()=>({}));setBusy(false);if(!response.ok){setError(data?.error?.message??"Retention run failed");return}setResult(data.affected);setMessage("Retention run completed.")}
  async function requestExport(event:FormEvent){event.preventDefault();setBusy(true);setError("");const response=await fetch("/api/v1/admin/governance/exports",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({exportType,reason:exportReason})}),data=await response.json().catch(()=>({}));setBusy(false);if(!response.ok){setError(data?.error?.message??"Could not request data export");return}setExportReason("");setMessage("Export requested. A different administrator must approve it.");await load()}
  async function reviewExport(id:string,action:"approve"|"reject"){const note=window.prompt(action==="reject"?"Rejection reason (required):":"Approval note (optional):","");if(note===null)return;setBusy(true);setError("");const response=await fetch(`/api/v1/admin/governance/exports/${id}/${action}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({note})}),data=await response.json().catch(()=>({}));setBusy(false);if(!response.ok){setError(data?.error?.message??`Could not ${action} export`);return}setMessage(action==="approve"?"Export approved and queued for generation.":"Export rejected.");await load()}
  async function downloadExport(id:string){setBusy(true);const response=await fetch(`/api/v1/admin/governance/exports/${id}/download`),data=await response.json().catch(()=>({}));setBusy(false);if(!response.ok){setError(data?.error?.message??"Could not download export");return}window.location.assign(data.url)}
  const activeHolds=holds.filter(hold=>hold.status==="ACTIVE");
  return <main className={styles.page}>
    <header><div><p>XSPACE ADMIN · COMPLIANCE</p><h1>Governance</h1><span>Control data lifecycle and preserve resources required for investigations.</span></div><nav><Link href="/admin">Dashboard</Link><Link href="/admin/audit">Audit</Link><Link href="/">← Workspace</Link></nav></header>
    {error&&<div className={styles.error} role="alert">{error}</div>}{message&&<div className={styles.notice} role="status">{message}</div>}
    <section className={styles.grid}>
      <form className={styles.card} onSubmit={savePolicy}><div className={styles.cardHead}><div><h2>Retention policy</h2><p>Days before tenant data becomes eligible for lifecycle processing.</p></div><b>POLICY</b></div>{policy?<div className={styles.fields}><NumberField label="Recordings" value={policy.recordingRetentionDays} min={1} onChange={value=>setPolicy({...policy,recordingRetentionDays:value})}/><NumberField label="Drive trash" value={policy.driveTrashRetentionDays} min={1} onChange={value=>setPolicy({...policy,driveTrashRetentionDays:value})}/><NumberField label="Chat messages" value={policy.chatRetentionDays} min={1} onChange={value=>setPolicy({...policy,chatRetentionDays:value})}/><NumberField label="Audit events" value={policy.auditRetentionDays} min={30} onChange={value=>setPolicy({...policy,auditRetentionDays:value})}/></div>:<p>Loading policy…</p>}<div className={styles.actions}><button disabled={busy||!policy}>Save policy</button><button type="button" className={styles.secondary} disabled={busy||!policy} onClick={()=>void runRetention()}>Run retention now</button></div>{result&&<dl className={styles.result}><div><dt>Chat</dt><dd>{result.chatMessages}</dd></div><div><dt>Attachments</dt><dd>{result.chatAttachments}</dd></div><div><dt>Recordings</dt><dd>{result.recordings}</dd></div><div><dt>Media objects</dt><dd>{result.recordingObjects}</dd></div><div><dt>Drive</dt><dd>{result.driveFiles}</dd></div><div><dt>Audit</dt><dd>{result.auditEvents}</dd></div></dl>}</form>
      <form className={styles.card} onSubmit={createHold}><div className={styles.cardHead}><div><h2>Create legal hold</h2><p>A hold prevents selected resources from retention processing.</p></div><b>LEGAL</b></div><label>Hold name<input value={name} minLength={2} maxLength={120} required onChange={event=>setName(event.target.value)} placeholder="Investigation 2026-08"/></label><label>Reason<textarea value={reason} minLength={2} maxLength={1000} required onChange={event=>setReason(event.target.value)} placeholder="Business or legal justification"/></label><button disabled={busy}>Activate legal hold</button></form>
    </section>
    <section className={styles.card}><div className={styles.cardHead}><div><h2>Protected resources</h2><p>Add a recording, Drive file, or complete chat conversation to an active hold.</p></div><b>{activeHolds.length} ACTIVE</b></div><form className={styles.resourceForm} onSubmit={addResource}><select required value={holdId} onChange={event=>setHoldId(event.target.value)}><option value="">Select active hold</option>{activeHolds.map(hold=><option key={hold.id} value={hold.id}>{hold.name}</option>)}</select><select value={resourceType} onChange={event=>setResourceType(event.target.value)}><option value="RECORDING">Recording</option><option value="DRIVE_FILE">Drive file</option><option value="CHAT_CONVERSATION">Chat conversation</option></select><input required value={resourceId} onChange={event=>setResourceId(event.target.value)} placeholder="Resource UUID"/><button disabled={busy||!holdId}>Add resource</button></form>
      <div className={styles.holds}>{holds.length?holds.map(hold=><article key={hold.id}><header><div><h3>{hold.name}</h3><p>{hold.reason}</p><small>Created {formatDate(hold.createdAt)}</small></div><span className={hold.status==="ACTIVE"?styles.active:styles.released}>{hold.status}</span></header><div className={styles.resources}>{hold.resources.length?hold.resources.map(resource=><div key={`${resource.type}-${resource.resourceId}`}><code>{resource.type} · {resource.resourceId}</code>{hold.status==="ACTIVE"&&<button disabled={busy} onClick={()=>void removeResource(hold.id,resource)}>Remove</button>}</div>):<p>No protected resources assigned.</p>}</div>{hold.status==="ACTIVE"&&<footer><button className={styles.danger} disabled={busy} onClick={()=>void releaseHold(hold.id)}>Release hold</button></footer>}</article>):<p className={styles.empty}>No legal holds have been created.</p>}</div>
    </section>
    <section className={`${styles.card} ${exportStyles.exports}`}><div className={styles.cardHead}><div><h2>Data exports</h2><p>Four-eyes approval is required before a private tenant archive is generated.</p></div><button className={exportStyles.refresh} disabled={busy} onClick={()=>void load()}>Refresh status</button></div><form className={exportStyles.request} onSubmit={requestExport}><select value={exportType} onChange={event=>setExportType(event.target.value)}><option value="FULL">Full tenant data</option><option value="AUDIT">Audit events</option><option value="DIRECTORY">Users and groups</option></select><input required minLength={5} maxLength={1000} value={exportReason} onChange={event=>setExportReason(event.target.value)} placeholder="Business reason for this export"/><button disabled={busy}>Request export</button></form><div className={exportStyles.list}>{exports.length?exports.map(item=><article key={item.id}><header><div><h3>{item.exportType} export</h3><p>{item.reason}</p><small>Requested by {item.requestedByName} · {formatDate(item.createdAt)}</small></div><span data-status={item.status}>{item.status}</span></header>{item.reviewedByName&&<p className={exportStyles.review}>Reviewed by {item.reviewedByName}{item.reviewNote?` · ${item.reviewNote}`:""}</p>}{item.sha256&&<code>SHA-256 {item.sha256}</code>}<footer>{item.canReview&&<><button disabled={busy} onClick={()=>void reviewExport(item.id,"approve")}>Approve</button><button className={exportStyles.reject} disabled={busy} onClick={()=>void reviewExport(item.id,"reject")}>Reject</button></>}{item.status==="READY"&&<button disabled={busy} onClick={()=>void downloadExport(item.id)}>Download {item.sizeBytes?formatBytes(item.sizeBytes):"archive"}</button>}{item.expiresAt&&<small>Expires {formatDate(item.expiresAt)}</small>}</footer></article>):<p className={styles.empty}>No export requests yet.</p>}</div></section>
  </main>
}

function NumberField({label,value,min,onChange}:{label:string;value:number;min:number;onChange:(value:number)=>void}){return <label>{label}<span><input type="number" min={min} max={3650} required value={value} onChange={event=>onChange(Number(event.target.value))}/><i>days</i></span></label>}
function formatDate(value:string){return new Intl.DateTimeFormat("en",{dateStyle:"medium",timeStyle:"short"}).format(new Date(value))}
function formatBytes(bytes:number){if(bytes<1024)return `${bytes} B`;if(bytes<1024**2)return `${(bytes/1024).toFixed(1)} KB`;return `${(bytes/1024**2).toFixed(1)} MB`}
