"use client";

import { useEffect, useState } from "react";
import styles from "../workspace-modules.module.css";

type Recording={id:string;status:string;startedAt:string;stoppedAt?:string;meetingTitle:string;joinCode:string;canDelete?:boolean};

export default function RecordingsPage(){
  const [recordings,setRecordings]=useState<Recording[]>([]),[error,setError]=useState(""),[loading,setLoading]=useState(true),[downloading,setDownloading]=useState(""),[deleting,setDeleting]=useState(""),[previewing,setPreviewing]=useState(""),[previews,setPreviews]=useState<Record<string,string>>({});
  useEffect(()=>{let active=true;void fetchRecordings().then(items=>{if(active)setRecordings(items)}).catch(reason=>{if(active)setError(reason instanceof Error?reason.message:"Could not load recordings")}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[]);
  async function refresh(){setLoading(true);setError("");try{setRecordings(await fetchRecordings())}catch(reason){setError(reason instanceof Error?reason.message:"Could not load recordings")}finally{setLoading(false)}}
  async function fileURL(recording:Recording,disposition:"inline"|"attachment"){const response=await fetch(`/api/v1/recordings/${encodeURIComponent(recording.id)}/file?disposition=${disposition}`),data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data?.error?.message??"Recording file is unavailable");return data.url as string}
  async function preview(recording:Recording){if(previews[recording.id]){setPreviews(items=>{const next={...items};delete next[recording.id];return next});return}setPreviewing(recording.id);setError("");try{const url=await fileURL(recording,"inline");setPreviews(items=>({...items,[recording.id]:url}))}catch(reason){setError(reason instanceof Error?reason.message:"Recording preview is unavailable")}finally{setPreviewing("")}}
  async function download(recording:Recording){setDownloading(recording.id);setError("");try{window.location.assign(await fileURL(recording,"attachment"))}catch(reason){setError(reason instanceof Error?reason.message:"Recording download is unavailable")}finally{setDownloading("")}}
  async function remove(recording:Recording){if(!window.confirm(`Delete the recording for “${recording.meetingTitle}”? This cannot be undone.`))return;setDeleting(recording.id);setError("");const response=await fetch(`/api/v1/recordings/${encodeURIComponent(recording.id)}`,{method:"DELETE"}),data=await response.json().catch(()=>({}));setDeleting("");if(!response.ok){setError(data?.error?.message??"Recording could not be deleted");return}setRecordings(items=>items.filter(item=>item.id!==recording.id));setPreviews(items=>{const next={...items};delete next[recording.id];return next})}
  return <main className={styles.page}><header className={styles.header}><div><p className={styles.eyebrow}>XSPACE CONTENT</p><h1>Recordings</h1><p className={styles.subtitle}>Secure meeting recordings available to your account.</p></div></header>{error&&<p className={styles.error} role="alert">{error}<button type="button" aria-label="Dismiss error" onClick={()=>setError("")}>×</button></p>}<section className={styles.panel}><div className={styles.toolbar}><strong>Recording library</strong><button className={styles.compact} onClick={()=>void refresh()}>Refresh</button></div><div className={`${styles.list} ${loading?styles.loading:""}`}>{loading?<p className={styles.empty}>Loading recording library…</p>:recordings.length===0?<p className={styles.empty}>No accessible recordings yet. Start recording from a live meeting.</p>:recordings.map(recording=><article key={recording.id} className={styles.recordingItem}><div><span className={styles.badge}>{recording.status}</span><h2>{recording.meetingTitle}</h2><p className={styles.recordMeta}><span>Started {formatDate(recording.startedAt)}</span>{recording.stoppedAt&&<span>Ended {formatDate(recording.stoppedAt)}</span>}</p><small>Meeting · {recording.joinCode}</small></div><div className={styles.recordActions}><button className={styles.compact} disabled={recording.status!=="READY"||previewing===recording.id} onClick={()=>void preview(recording)}>{previewing===recording.id?"Opening…":previews[recording.id]?"Close player":"Play"}</button><button className={styles.compact} disabled={recording.status!=="READY"||downloading===recording.id} onClick={()=>void download(recording)}>{downloading===recording.id?"Preparing…":"Download MP4"}</button>{recording.canDelete&&<button className={styles.danger} disabled={deleting===recording.id||recording.status==="RECORDING"||recording.status==="STARTING"||recording.status==="STOPPING"} onClick={()=>void remove(recording)}>{deleting===recording.id?"Deleting…":"Delete"}</button>}</div>{previews[recording.id]&&<div className={styles.recordingPlayer}><video controls preload="metadata" src={previews[recording.id]}>Your browser does not support video playback.</video><p>Private preview link expires automatically after 15 minutes.</p></div>}</article>)}</div></section></main>;
}
async function fetchRecordings():Promise<Recording[]>{const response=await fetch("/api/v1/recordings"),data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data?.error?.message??"Could not load recordings");return data.recordings??[]}
function formatDate(value:string){return new Intl.DateTimeFormat("en",{dateStyle:"medium",timeStyle:"short"}).format(new Date(value))}
