"use client";
/* eslint-disable react-hooks/set-state-in-effect -- async loader updates state only after awaited API responses. */

import Link from "next/link";
import { FormEvent, useCallback, useEffect, useState } from "react";
import styles from "./roles.module.css";

type Role={id:string;name:string;description:string;permissions:string[];memberCount:number};
type User={id:string;username:string;displayName:string;status:string};

export default function RolesPage(){
  const[roles,setRoles]=useState<Role[]>([]),[catalog,setCatalog]=useState<string[]>([]),[users,setUsers]=useState<User[]>([]),[selected,setSelected]=useState<string[]>([]),[error,setError]=useState(""),[notice,setNotice]=useState("");
  const load=useCallback(async()=>{const[roleResponse,userResponse]=await Promise.all([fetch("/api/v1/admin/roles"),fetch("/api/v1/admin/users")]);const[a,b]=await Promise.all([roleResponse.json().catch(()=>({})),userResponse.json().catch(()=>({}))]);if(!roleResponse.ok)throw new Error(a?.error?.message??"Could not load roles");if(!userResponse.ok)throw new Error(b?.error?.message??"Could not load users");setRoles(a.roles??[]);setCatalog(a.permissionCatalog??[]);setUsers(b.users??[])},[]);
  useEffect(()=>{void load().catch(reason=>setError(reason instanceof Error?reason.message:"Could not load RBAC"))},[load]);
  async function create(event:FormEvent<HTMLFormElement>){event.preventDefault();const formElement=event.currentTarget,form=new FormData(formElement);const response=await fetch("/api/v1/admin/roles",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:form.get("name"),description:form.get("description"),permissions:selected})});const data=await response.json().catch(()=>({}));if(!response.ok){setError(data?.error?.message??"Could not create role");return}formElement.reset();setSelected([]);setNotice("Custom role created.");await load()}
  async function assign(role:Role,method:"PUT"|"DELETE"){const username=window.prompt(`${method==="PUT"?"Assign":"Remove"} ${role.name} ${method==="PUT"?"to":"from"} username:\n${users.filter(item=>item.status==="ACTIVE").map(item=>item.username).join(", ")}`)?.trim();if(!username)return;const user=users.find(item=>item.username===username);if(!user){setError("Username not found.");return}const response=await fetch(`/api/v1/admin/roles/${role.id}/users/${user.id}`,{method});if(!response.ok){const data=await response.json().catch(()=>({}));setError(data?.error?.message??"Could not update assignment");return}setNotice(`${role.name} ${method==="PUT"?"assigned to":"removed from"} ${user.displayName}.`);await load()}
  async function remove(role:Role){if(!window.confirm(`Delete custom role ${role.name}?`))return;const response=await fetch(`/api/v1/admin/roles/${role.id}`,{method:"DELETE"});if(response.ok){setNotice("Custom role deleted.");await load()}else{const data=await response.json().catch(()=>({}));setError(data?.error?.message??"Could not delete role")}}
  return <main className={styles.page}><header><div><p>XSPACE ADMIN · RBAC</p><h1>Roles & permissions</h1><span>Delegate precise capabilities without granting full tenant administration.</span></div><nav><Link href="/admin">Dashboard</Link><Link href="/admin/users">Users</Link><Link href="/admin/audit">Audit</Link></nav></header>{(error||notice)&&<div className={error?styles.error:styles.notice} role={error?"alert":"status"}>{error||notice}<button onClick={()=>{setError("");setNotice("")}}>×</button></div>}<section className={styles.layout}><form className={styles.form} onSubmit={create}><h2>Create custom role</h2><p>Role administration and platform permissions cannot be delegated.</p><label>Role name<input name="name" minLength={2} maxLength={80} required placeholder="Compliance reviewer"/></label><label>Description<textarea name="description" maxLength={300} placeholder="What this role is responsible for"/></label><fieldset><legend>Permissions</legend>{catalog.map(permission=><label key={permission}><input type="checkbox" checked={selected.includes(permission)} onChange={event=>setSelected(items=>event.target.checked?[...items,permission]:items.filter(item=>item!==permission))}/><span><strong>{permission}</strong><small>{permissionDescription(permission)}</small></span></label>)}</fieldset><button>Create role</button></form><section className={styles.roles}><div><h2>Tenant custom roles</h2><p>{roles.length} roles configured</p></div>{roles.length?roles.map(role=><article key={role.id}><header><div><h3>{role.name}</h3><p>{role.description||"Custom tenant role"}</p></div><b>{role.memberCount} members</b></header><div className={styles.permissions}>{role.permissions.map(item=><span key={item}>{item}</span>)}</div><footer><button onClick={()=>void assign(role,"PUT")}>Assign user</button><button onClick={()=>void assign(role,"DELETE")}>Remove user</button><button className={styles.delete} onClick={()=>void remove(role)}>Delete</button></footer></article>):<p className={styles.empty}>No custom roles yet.</p>}</section></section></main>
}

function permissionDescription(value:string){return ({"analytics.read":"View tenant usage and meeting analytics","audit.read":"Review tenant audit events","groups.manage":"Create groups and manage membership","identity.manage":"Configure enterprise identity providers","meeting.create":"Create and schedule meetings","meeting.moderate":"Moderate any tenant meeting","policy.manage":"Manage meeting security policies","users.manage":"Create and manage tenant users"} as Record<string,string>)[value]??value}
