"use client";
import {useConnectionQualityIndicator,useConnectionState,useLocalParticipant} from "@livekit/components-react";
import {ConnectionQuality,ConnectionState,LocalVideoTrack,VideoQuality} from "livekit-client";
import {useEffect,useRef,useState} from "react";
type Metrics={bitrate:number;rtt:number|null;jitter:number|null;loss:number|null;fps:number|null;codec:string;layer:string};
type OutboundStats=RTCStats&{kind?:string;isRemote?:boolean;remoteId?:string;codecId?:string;bytesSent?:number;packetsSent?:number;framesPerSecond?:number;rid?:string};type RemoteStats=RTCStats&{packetsLost?:number;roundTripTime?:number;jitter?:number};type CodecStats=RTCStats&{mimeType?:string};
const empty:Metrics={bitrate:0,rtt:null,jitter:null,loss:null,fps:null,codec:"—",layer:"—"};
export default function NetworkStatus(){
 const connection=useConnectionState();const {localParticipant,cameraTrack,isCameraEnabled}=useLocalParticipant();const {quality}=useConnectionQualityIndicator({participant:localParticipant});const [low,setLow]=useState(false);const [auto,setAuto]=useState(true);const [restoreCamera,setRestoreCamera]=useState(false);const [metrics,setMetrics]=useState<Metrics>(empty);const [profile,setProfile]=useState("Auto / High");const [demo,setDemo]=useState("");const previous=useRef({bytes:0,time:0});const poorSamples=useRef(0);const stableSamples=useRef(0);const demoTimers=useRef<number[]>([]);
 useEffect(()=>{let active=true;const update=async()=>{const track=cameraTrack?.track as LocalVideoTrack|undefined;if(!track){if(active)setMetrics(empty);return}const report=await track.getRTCStatsReport();if(!report)return;let outbound:OutboundStats|undefined,remote:RemoteStats|undefined,codec="—";report.forEach((stat:RTCStats)=>{const candidate=stat as OutboundStats;if(stat.type==="outbound-rtp"&&candidate.kind==="video"&&!candidate.isRemote)outbound=candidate});if(outbound){remote=report.get(outbound.remoteId??"") as RemoteStats|undefined;const codecStat=report.get(outbound.codecId??"") as CodecStats|undefined;codec=codecStat?.mimeType?.replace("video/","")??"—";const now=outbound.timestamp,bytes=outbound.bytesSent??0,elapsed=(now-previous.current.time)/1000;const bitrate=previous.current.time&&elapsed>0?Math.max(0,Math.round((bytes-previous.current.bytes)*8/elapsed/1000)):0;previous.current={bytes,time:now};const sent=outbound.packetsSent??0,lost=remote?.packetsLost??0;const loss=sent+lost>0?Math.max(0,Number((lost/(sent+lost)*100).toFixed(1))):null;if(active)setMetrics({bitrate,rtt:remote?.roundTripTime!=null?Math.round(remote.roundTripTime*1000):null,jitter:remote?.jitter!=null?Math.round(remote.jitter*1000):null,loss,fps:outbound.framesPerSecond??null,codec,layer:outbound.rid?.toUpperCase()??(track.isSimulcast?"AUTO":"SINGLE")})}};void update();const timer=setInterval(update,1500);return()=>{active=false;clearInterval(timer)}},[cameraTrack]);
 useEffect(()=>{const track=cameraTrack?.track as LocalVideoTrack|undefined;if(!auto||low||!track)return;if(quality===ConnectionQuality.Poor){poorSamples.current+=1;stableSamples.current=0}else if(quality===ConnectionQuality.Excellent){stableSamples.current+=1;poorSamples.current=0}else{poorSamples.current=0;stableSamples.current=Math.max(0,stableSamples.current-1)}if(poorSamples.current>=3){track.setPublishingQuality(VideoQuality.LOW);setProfile("Adaptive / Low");poorSamples.current=0}if(stableSamples.current===3){track.setPublishingQuality(VideoQuality.MEDIUM);setProfile("Recovering / Medium")}if(stableSamples.current>=6){track.setPublishingQuality(VideoQuality.HIGH);setProfile("Stable / High");stableSamples.current=0}},[quality,auto,low,cameraTrack]);
 useEffect(()=>()=>demoTimers.current.forEach(clearTimeout),[]);
 const toggle=async()=>{if(!low){setRestoreCamera(isCameraEnabled);if(isCameraEnabled)await localParticipant.setCameraEnabled(false);setProfile("Audio priority");setLow(true)}else{if(restoreCamera)await localParticipant.setCameraEnabled(true,{resolution:{width:640,height:360},frameRate:15});setProfile("Recovery / 360p");setLow(false)}};const runDemo=()=>{const track=cameraTrack?.track as LocalVideoTrack|undefined;if(!track||demo)return;const phase=(delay:number,name:string,videoQuality:VideoQuality)=>demoTimers.current.push(window.setTimeout(()=>{setDemo(name);track.setPublishingQuality(videoQuality);setProfile(`${name} / ${videoQuality===VideoQuality.HIGH?"High":videoQuality===VideoQuality.MEDIUM?"Medium":"Low"}`)},delay));phase(0,"Normal",VideoQuality.HIGH);phase(3000,"Limited",VideoQuality.MEDIUM);phase(6000,"Poor",VideoQuality.LOW);phase(9000,"Recovery",VideoQuality.MEDIUM);phase(12000,"Stable",VideoQuality.HIGH);demoTimers.current.push(window.setTimeout(()=>setDemo(""),15000))};
 const label=quality===ConnectionQuality.Excellent?"Excellent":quality===ConnectionQuality.Good?"Good":quality===ConnectionQuality.Poor?"Poor":"Unknown",dimensions=cameraTrack?.dimensions;
 return <><div className={`network-pill quality-${label.toLowerCase()}`}><span>{label==="Excellent"?"▮▮▮":label==="Good"?"▮▮▯":label==="Poor"?"▮▯▯":"▯▯▯"}</span><strong>{label}</strong><small>{metrics.bitrate?`${metrics.bitrate} kbps`:"Audio priority"}</small><button onClick={toggle}>{low?"Exit low bandwidth":"Low bandwidth"}</button></div><div className="adaptive-controls"><button className={auto?"active":""} onClick={()=>setAuto(!auto)}>Adaptive {auto?"ON":"OFF"}</button><button onClick={runDemo} disabled={Boolean(demo)}>{demo||"Run network demo"}</button><span>{profile}</span></div>{low&&<div className="bandwidth-notice"><b>Low-bandwidth mode active</b><span>Camera paused · audio prioritized · reduced data usage</span></div>}<div className="network-metrics"><span>State <b>{connection}</b></span><span>RTT <b>{metrics.rtt!=null?`${metrics.rtt} ms`:"—"}</b></span><span>Jitter <b>{metrics.jitter!=null?`${metrics.jitter} ms`:"—"}</b></span><span>Loss <b>{metrics.loss!=null?`${metrics.loss}%`:"—"}</b></span><span>Bitrate <b>{metrics.bitrate?`${metrics.bitrate}k`:"—"}</b></span><span>FPS <b>{metrics.fps??"—"}</b></span><span>Resolution <b>{dimensions?`${dimensions.width}×${dimensions.height}`:"Off"}</b></span><span>Codec <b>{metrics.codec}</b></span><span>Layer <b>{metrics.layer}</b></span></div>{(connection===ConnectionState.Reconnecting||connection===ConnectionState.SignalReconnecting)&&<div className="reconnect-overlay"><i className="spinner"/><strong>Reconnecting your meeting</strong><span>Your media settings are preserved. Xpace is finding the best route.</span></div>}</>
}
