"use client";
/* eslint-disable react-hooks/set-state-in-effect -- polling callbacks update state only after awaited network responses. */
import Link from "next/link";
import { CspImage as Image } from "@/components/csp-image";
import { useParams, useRouter, useSearchParams } from "next/navigation";
import { useCallback, useEffect, useRef, useState } from "react";
import { LiveKitRoom } from "@livekit/components-react";
import { DisconnectReason, type RoomOptions } from "livekit-client";
import xpaceLogo from "../../../../asset/Logo-transparent.png";
import NetworkStatus from "./network-status";
import XspaceVideoConference from "./xspace-video-conference";
type Credentials={token:string;serverUrl:string;roomName:string};type Participant={id:string;userId?:string;avatarUrl?:string|null;displayName:string;role:string;status:string};
const roomOptions:RoomOptions={adaptiveStream:{pixelDensity:"screen"},dynacast:true,publishDefaults:{simulcast:true,scalabilityMode:"L3T3_KEY",dtx:true,red:true}};
export default function MeetingRoom(){
 const {code}=useParams<{code:string}>();const router=useRouter();const initiallyWaiting=useSearchParams().get("status")==="waiting_room";const leaving=useRef(false);const tokenFailures=useRef(0);const reconnectTimer=useRef<number|undefined>(undefined);const stableTimer=useRef<number|undefined>(undefined);const [tokenAttempt,setTokenAttempt]=useState(0);const [status,setStatus]=useState(initiallyWaiting?"WAITING_ROOM":"JOINED");const [isHost,setIsHost]=useState(false);const [credentials,setCredentials]=useState<Credentials|null>(null);const [error,setError]=useState("");const [panel,setPanel]=useState(false);const [moreOpen,setMoreOpen]=useState(false);const [codeCopied,setCodeCopied]=useState(false);const [diagnosticsOpen,setDiagnosticsOpen]=useState(false);const [locked,setLocked]=useState(false);const [ended,setEnded]=useState(false);const [recording,setRecording]=useState(false);const [recordingBusy,setRecordingBusy]=useState(false);const [waitingRequests,setWaitingRequests]=useState<Participant[]>([]);const [waitingActionError,setWaitingActionError]=useState("");
 useEffect(()=>{let active=true;const check=async()=>{if(document.visibilityState==="hidden")return;try{const response=await fetch(`/api/v1/meetings/${encodeURIComponent(code.toUpperCase())}/participant`);const data=await response.json();if(response.ok&&active){setStatus(data.participant.status);setIsHost(data.isHost);setError(current=>current==="Could not reach Xspace API"?"":current)}else if(!response.ok&&active)setError(data?.error?.message??"Could not verify participant")}catch{/* A later poll or realtime reconnect retries without destroying the active room. */}};void check();const timer=window.setInterval(check,status==="WAITING_ROOM"?2000:5000);return()=>{active=false;clearInterval(timer)}},[code,status]);
 useEffect(()=>{if(!["JOINED","DISCONNECTED"].includes(status)||credentials)return;let active=true;let retryTimer:number|undefined;fetch(`/api/v1/meetings/${encodeURIComponent(code.toUpperCase())}/token`,{method:"POST",headers:{"Content-Type":"application/json"},body:"{}"}).then(async response=>{const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data?.error?.message??"Could not connect to realtime service");if(active){setError("");setCredentials(data)}}).catch(reason=>{if(!active)return;tokenFailures.current+=1;if(tokenFailures.current>=5)setError(reason instanceof Error?reason.message:"Could not connect to realtime service");else retryTimer=window.setTimeout(()=>setTokenAttempt(value=>value+1),Math.min(1000*tokenFailures.current,4000))});return()=>{active=false;if(retryTimer)window.clearTimeout(retryTimer)}},[code,status,credentials,tokenAttempt]);
 useEffect(()=>{if(!isHost)return;let active=true;const check=async()=>{if(document.visibilityState==="hidden")return;const response=await fetch(`/api/v1/meetings/${encodeURIComponent(code.toUpperCase())}/recordings`);const data=await response.json().catch(()=>({recordings:[]}));if(active&&response.ok)setRecording(data.recordings?.some((item:{status:string})=>["STARTING","RECORDING","STOPPING"].includes(item.status))??false)};void check();const timer=setInterval(check,10000);return()=>{active=false;clearInterval(timer)}},[code,isHost]);
 useEffect(()=>{if(!isHost)return;let active=true;const check=async()=>{if(document.visibilityState==="hidden")return;try{const response=await fetch(`/api/v1/meetings/${encodeURIComponent(code.toUpperCase())}/participants`);const data=await response.json().catch(()=>({participants:[]}));if(active&&response.ok)setWaitingRequests(uniqueParticipants(data.participants??[]).filter((participant:Participant)=>participant.status==="WAITING_ROOM"))}catch{/* The next poll retries without interrupting the live meeting. */}};void check();const timer=setInterval(check,5000);return()=>{active=false;clearInterval(timer)}},[code,isHost]);
 useEffect(()=>{if(!moreOpen)return;const close=(event:KeyboardEvent)=>{if(event.key==="Escape")setMoreOpen(false)};document.addEventListener("keydown",close);return()=>document.removeEventListener("keydown",close)},[moreOpen]);
 const meetingAction=async(action:"lock"|"unlock"|"end")=>{if(action==="end"&&!window.confirm("End this meeting for everyone?"))return;const response=await fetch(`/api/v1/meetings/${encodeURIComponent(code.toUpperCase())}/moderation/${action}`,{method:"POST",headers:{"Content-Type":"application/json"},body:"{}"});const data=await response.json().catch(()=>({}));if(!response.ok){setError(data?.error?.message??"Meeting action failed");return}if(action==="end")router.push("/");else setLocked(action==="lock")};
 const recordingAction=async()=>{setRecordingBusy(true);const suffix=recording?"/stop":"";const response=await fetch(`/api/v1/meetings/${encodeURIComponent(code.toUpperCase())}/recordings${suffix}`,{method:"POST",headers:{"Content-Type":"application/json"},body:"{}"});const data=await response.json().catch(()=>({}));setRecordingBusy(false);if(!response.ok){setError(data?.error?.message??"Recording action failed");return}setRecording(!recording)};
 const admitWaiting=async(participant:Participant)=>{setWaitingActionError("");const response=await fetch(`/api/v1/meetings/${encodeURIComponent(code.toUpperCase())}/participants/${encodeURIComponent(participant.id)}/admit`,{method:"POST",headers:{"Content-Type":"application/json"},body:"{}"});const data=await response.json().catch(()=>({}));if(!response.ok){setWaitingActionError(data?.error?.message??"Could not admit participant");return}setWaitingRequests(items=>items.filter(item=>item.id!==participant.id))};
 const copyMeetingCode=async()=>{const value=code.toUpperCase();try{await navigator.clipboard.writeText(value);setCodeCopied(true);window.setTimeout(()=>setCodeCopied(false),1800)}catch{window.prompt("Copy meeting code",value)}setMoreOpen(false)};
 const leaveRoom=useCallback(async()=>{if(leaving.current)return;leaving.current=true;try{await fetch(`/api/v1/meetings/${encodeURIComponent(code.toUpperCase())}/leave`,{method:"POST",keepalive:true})}finally{router.push("/")}},[code,router]);
 const recoverRealtime=useCallback((message:string)=>{if(leaving.current||reconnectTimer.current!==undefined)return;if(stableTimer.current!==undefined){window.clearTimeout(stableTimer.current);stableTimer.current=undefined}tokenFailures.current+=1;if(tokenFailures.current>=5){setError(message);return}setError("");setCredentials(null);reconnectTimer.current=window.setTimeout(()=>{reconnectTimer.current=undefined;setTokenAttempt(value=>value+1)},Math.min(1000*tokenFailures.current,4000))},[]);
 useEffect(()=>()=>{if(reconnectTimer.current!==undefined)window.clearTimeout(reconnectTimer.current);if(stableTimer.current!==undefined)window.clearTimeout(stableTimer.current)},[]);
 if(ended)return <MessageState code={code} title="This meeting has ended" message="Your media connection is closed and your meeting history has been updated."/>;if(status==="WAITING_ROOM")return <RoomState code={code} onLeave={leaveRoom}/>;if(status==="REMOVED")return <MessageState code={code} title="Entry was not approved" message="The host declined or removed your request to join."/>;if(status==="LEFT")return <MessageState code={code} title="Reconnect window expired" message="Return to device preview to rejoin this meeting."/>;if(error)return <MessageState code={code} title="Realtime room is unavailable" message={error}/>;if(!credentials)return <main className="room-page"><div className="room-brand"><Brand/></div><section className="room-state"><i className="spinner"/><p>RECONNECTING SECURELY</p><h1>Restoring your realtime room</h1><span>Xspace is retrying the best media route without ending your meeting.</span></section></main>;
 return <main className="live-room" data-lk-theme="default"><LiveKitRoom token={credentials.token} serverUrl={credentials.serverUrl} options={roomOptions} connect audio video onConnected={()=>{if(stableTimer.current!==undefined)window.clearTimeout(stableTimer.current);stableTimer.current=window.setTimeout(()=>{tokenFailures.current=0;stableTimer.current=undefined},10000)}} onDisconnected={reason=>{if(reason===DisconnectReason.ROOM_DELETED)setEnded(true);else if(reason!==DisconnectReason.CLIENT_INITIATED)recoverRealtime("Could not restore the realtime connection")}} onError={reason=>recoverRealtime(reason.message)}><header className="live-header"><Brand/><div className="meeting-identity"><span><i/> LIVE</span><button className="meeting-code" aria-label={`Copy meeting code ${code.toUpperCase()}`} title="Copy meeting code" onClick={()=>void copyMeetingCode()}>{codeCopied?"Copied!":code.toUpperCase()}</button></div><button className="mobile-more" aria-label="Open meeting actions" aria-expanded={moreOpen} onClick={()=>setMoreOpen(value=>!value)}>•••</button><nav className={`live-actions ${moreOpen?"open":""}`} aria-label="Meeting actions"><button className="copy-code-button" onClick={()=>void copyMeetingCode()}>{codeCopied?"✓ Code copied":"Copy meeting code"}</button>{isHost&&<><button className={`record-button ${recording?"active":""}`} disabled={recordingBusy} onClick={recordingAction}><i/>{recordingBusy?"Please wait":recording?"Stop recording":"Record"}</button><button className="policy-button" onClick={()=>meetingAction(locked?"unlock":"lock")}>{locked?"Unlock":"Lock"}</button><button className="people-button" onClick={()=>{setPanel(!panel);setMoreOpen(false)}}>Participants{waitingRequests.length>0&&<b className="waiting-count">{waitingRequests.length}</b>}</button><button className="end-button" onClick={()=>meetingAction("end")}>End for all</button></>}<button className="diagnostics-button" aria-expanded={diagnosticsOpen} onClick={()=>{setDiagnosticsOpen(value=>!value);setMoreOpen(false)}}>Diagnostics</button><button className="leave-button" onClick={()=>void leaveRoom()}>Leave room</button></nav></header>{moreOpen&&<button className="live-actions-dismiss" aria-label="Close meeting actions" onClick={()=>setMoreOpen(false)}/>}<XspaceVideoConference/><section className={`room-diagnostics ${diagnosticsOpen?"open":""}`} aria-label="Network diagnostics"><NetworkStatus/></section>{recording&&<div className="recording-notice"><i/> Recording in progress · stored privately</div>}{isHost&&!panel&&waitingRequests.length>0&&<WaitingNotice items={waitingRequests} error={waitingActionError} onView={()=>setPanel(true)} onAdmit={admitWaiting}/>} {isHost&&panel&&<HostPanel code={code} onClose={()=>setPanel(false)}/>}</LiveKitRoom></main>
}
function WaitingNotice({items,error,onView,onAdmit}:{items:Participant[];error:string;onView:()=>void;onAdmit:(participant:Participant)=>void}){const first=items[0];return <aside className="waiting-admit-notice" role="alert" aria-live="assertive"><Avatar name={first.displayName} avatarUrl={first.avatarUrl}/><div><strong>{first.displayName}</strong><span>{items.length===1?"wants to join this meeting":`and ${items.length-1} others want to join`}{error&&<em>{error}</em>}</span></div><button className="view-waiting" onClick={onView}>View</button><button className="admit-waiting" onClick={()=>onAdmit(first)}>Admit</button></aside>}
function HostPanel({code,onClose}:{code:string;onClose:()=>void}){const [items,setItems]=useState<Participant[]>([]);const [error,setError]=useState("");const load=useCallback(async()=>{if(document.visibilityState==="hidden")return;try{const response=await fetch(`/api/v1/meetings/${encodeURIComponent(code.toUpperCase())}/participants`);const data=await response.json();if(!response.ok)throw new Error(data?.error?.message??"Could not load participants");setItems(uniqueParticipants(data.participants??[]));setError("")}catch(reason){setError(reason instanceof Error?reason.message:"Could not load participants")}},[code]);useEffect(()=>{void load();const timer=setInterval(load,5000);return()=>clearInterval(timer)},[load]);const act=async(id:string,action:string)=>{const response=await fetch(`/api/v1/meetings/${encodeURIComponent(code.toUpperCase())}/participants/${encodeURIComponent(id)}/${action}`,{method:"POST",headers:{"Content-Type":"application/json"},body:"{}"});const data=await response.json().catch(()=>({}));if(!response.ok)setError(data?.error?.message??"Action failed");await load()};const waiting=items.filter(p=>p.status==="WAITING_ROOM"),joined=items.filter(p=>["JOINED","DISCONNECTED"].includes(p.status));return <aside className="host-panel"><header><div><strong>Participants</strong><span>{items.length} in this meeting</span></div><button onClick={onClose}>×</button></header>{error&&<p className="host-error">{error}</p>}<section><h2>WAITING ROOM <span>{waiting.length}</span></h2>{waiting.length===0?<p className="empty-list">No one is waiting</p>:waiting.map(p=><article key={p.id}><Avatar name={p.displayName} avatarUrl={p.avatarUrl}/><div><strong>{p.displayName}</strong><span>Waiting to join</span></div><button className="admit" onClick={()=>act(p.id,"admit")}>Admit</button><button className="reject" onClick={()=>act(p.id,"reject")}>Reject</button></article>)}</section><section><h2>IN THE MEETING <span>{joined.length}</span></h2>{joined.map(p=><article key={p.id}><Avatar name={p.displayName} avatarUrl={p.avatarUrl}/><div><strong>{p.displayName}</strong><span>{p.role.replace("_"," ")}{p.status==="DISCONNECTED"?" · reconnecting":""}</span></div>{p.role!=="HOST"&&<button onClick={()=>act(p.id,"mute")}>Mute</button>}{p.role==="MEMBER"&&<button onClick={()=>act(p.id,"promote")}>Make co-host</button>}{p.role!=="HOST"&&<button className="reject" onClick={()=>act(p.id,"remove")}>Remove</button>}</article>)}</section></aside>}
function uniqueParticipants(items:Participant[]){const seen=new Set<string>();return items.filter(item=>{const key=item.userId||item.id;if(seen.has(key))return false;seen.add(key);return true})}
function Avatar({name,avatarUrl}:{name:string;avatarUrl?:string|null}){const initials=name.trim().split(/\s+/).filter(Boolean).map(word=>word[0]).slice(0,2).join("").toUpperCase()||"?";return <span className="participant-avatar" aria-label={`${name} profile`} title={name}>{avatarUrl?<Image src={avatarUrl} alt="" width={34} height={34} unoptimized/>:initials}</span>}
function RoomState({code,onLeave}:{code:string;onLeave:()=>Promise<void>}){return <main className="room-page"><div className="room-brand"><Brand/></div><section className="room-state"><div className="waiting-pulse"><span>AU</span></div><p>WAITING ROOM</p><h1>The host will let you in soon</h1><span>This page updates automatically. Your camera and microphone remain off while you wait.</span><div><b>Meeting code</b><strong>{code.toUpperCase()}</strong></div><Link href="/" onClick={event=>{event.preventDefault();void onLeave()}}>Leave and return to dashboard</Link></section><footer><i/> Securely connected to Xspace · Jakarta region</footer></main>}
function MessageState({code,title,message}:{code:string;title:string;message:string}){return <main className="room-page"><div className="room-brand"><Brand/></div><section className="room-state"><div className="room-error">!</div><p>MEETING NOTICE</p><h1>{title}</h1><span>{message}</span><Link href={`/meet/${encodeURIComponent(code)}/prejoin`}>Return to device preview</Link></section></main>}
function Brand(){return <Image className="room-brand-logo" src={xpaceLogo} alt="Xspace" priority sizes="140px"/>}
