"use client";
/* eslint-disable react-hooks/set-state-in-effect -- polling callbacks update state only after awaited network responses. */
import Link from "next/link";
import { useParams, useRouter, useSearchParams } from "next/navigation";
import { useCallback, useEffect, useState } from "react";
import { LiveKitRoom, VideoConference } from "@livekit/components-react";
import { DisconnectReason, type RoomOptions } from "livekit-client";
import NetworkStatus from "./network-status";
type Credentials={token:string;serverUrl:string;roomName:string};type Participant={id:string;displayName:string;role:string;status:string};
const roomOptions:RoomOptions={adaptiveStream:{pixelDensity:"screen"},dynacast:true,publishDefaults:{simulcast:true,scalabilityMode:"L3T3_KEY",dtx:true,red:true}};
export default function MeetingRoom(){
 const {code}=useParams<{code:string}>();const router=useRouter();const initiallyWaiting=useSearchParams().get("status")==="waiting_room";const [status,setStatus]=useState(initiallyWaiting?"WAITING_ROOM":"JOINED");const [isHost,setIsHost]=useState(false);const [credentials,setCredentials]=useState<Credentials|null>(null);const [error,setError]=useState("");const [panel,setPanel]=useState(false);const [locked,setLocked]=useState(false);const [ended,setEnded]=useState(false);const [recording,setRecording]=useState(false);const [recordingBusy,setRecordingBusy]=useState(false);
 useEffect(()=>{let active=true;const check=async()=>{try{const response=await fetch(`/api/v1/meetings/${encodeURIComponent(code.toUpperCase())}/participant`);const data=await response.json();if(response.ok&&active){setStatus(data.participant.status);setIsHost(data.isHost)}else if(!response.ok&&active)setError(data?.error?.message??"Could not verify participant")}catch{if(active)setError("Could not reach Xpace API")}};void check();const timer=window.setInterval(check,2000);return()=>{active=false;clearInterval(timer)}},[code]);
 useEffect(()=>{if(status!=="JOINED"||credentials)return;let active=true;fetch(`/api/v1/meetings/${encodeURIComponent(code.toUpperCase())}/token`,{method:"POST",headers:{"Content-Type":"application/json"},body:"{}"}).then(async response=>{const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data?.error?.message??"Could not connect to realtime service");if(active)setCredentials(data)}).catch(reason=>{if(active)setError(reason instanceof Error?reason.message:"Could not connect to realtime service")});return()=>{active=false}},[code,status,credentials]);
 useEffect(()=>{if(!isHost)return;let active=true;const check=async()=>{const response=await fetch(`/api/v1/meetings/${encodeURIComponent(code.toUpperCase())}/recordings`);const data=await response.json().catch(()=>({recordings:[]}));if(active&&response.ok)setRecording(data.recordings?.some((item:{Status:string})=>["STARTING","RECORDING","STOPPING"].includes(item.Status))??false)};void check();const timer=setInterval(check,3000);return()=>{active=false;clearInterval(timer)}},[code,isHost]);
 const meetingAction=async(action:"lock"|"unlock"|"end")=>{if(action==="end"&&!window.confirm("End this meeting for everyone?"))return;const response=await fetch(`/api/v1/meetings/${encodeURIComponent(code.toUpperCase())}/moderation/${action}`,{method:"POST",headers:{"Content-Type":"application/json"},body:"{}"});const data=await response.json().catch(()=>({}));if(!response.ok){setError(data?.error?.message??"Meeting action failed");return}if(action==="end")router.push("/");else setLocked(action==="lock")};
 const recordingAction=async()=>{setRecordingBusy(true);const suffix=recording?"/stop":"";const response=await fetch(`/api/v1/meetings/${encodeURIComponent(code.toUpperCase())}/recordings${suffix}`,{method:"POST",headers:{"Content-Type":"application/json"},body:"{}"});const data=await response.json().catch(()=>({}));setRecordingBusy(false);if(!response.ok){setError(data?.error?.message??"Recording action failed");return}setRecording(!recording)};
 if(ended)return <MessageState code={code} title="This meeting has ended" message="Your media connection is closed and your meeting history has been updated."/>;if(status==="WAITING_ROOM")return <RoomState code={code}/>;if(status==="REMOVED")return <MessageState code={code} title="Entry was not approved" message="The host declined or removed your request to join."/>;if(error)return <MessageState code={code} title="Realtime room is unavailable" message={error}/>;if(!credentials)return <main className="room-page"><div className="room-brand"><Brand/></div><section className="room-state"><i className="spinner"/><p>CONNECTING SECURELY</p><h1>Preparing your realtime room</h1><span>Xpace is negotiating the best media route for your network.</span></section></main>;
 return <main className="live-room" data-lk-theme="default"><LiveKitRoom token={credentials.token} serverUrl={credentials.serverUrl} options={roomOptions} connect audio video onDisconnected={reason=>{void fetch(`/api/v1/meetings/${encodeURIComponent(code.toUpperCase())}/leave`,{method:"POST"});if(reason===DisconnectReason.ROOM_DELETED)setEnded(true);else setError("The realtime connection closed before the meeting ended. Check your network and return to device preview to try again.")}} onError={reason=>setError(reason.message)}><header className="live-header"><Brand/><div><span><i/> LIVE</span><strong>{code.toUpperCase()}</strong></div>{isHost&&<><button className={`record-button ${recording?"active":""}`} disabled={recordingBusy} onClick={recordingAction}><i/>{recordingBusy?"Please wait":recording?"Stop recording":"Record"}</button><button className="policy-button" onClick={()=>meetingAction(locked?"unlock":"lock")}>{locked?"Unlock":"Lock"}</button><button className="people-button" onClick={()=>setPanel(!panel)}>Participants</button><button className="end-button" onClick={()=>meetingAction("end")}>End for all</button></>}<button onClick={()=>router.push("/")}>Leave room</button></header><VideoConference/><NetworkStatus/>{recording&&<div className="recording-notice"><i/> Recording in progress · stored privately</div>}{isHost&&panel&&<HostPanel code={code} onClose={()=>setPanel(false)}/>}</LiveKitRoom></main>
}
function HostPanel({code,onClose}:{code:string;onClose:()=>void}){const [items,setItems]=useState<Participant[]>([]);const [error,setError]=useState("");const load=useCallback(async()=>{try{const response=await fetch(`/api/v1/meetings/${encodeURIComponent(code.toUpperCase())}/participants`);const data=await response.json();if(!response.ok)throw new Error(data?.error?.message??"Could not load participants");setItems(data.participants);setError("")}catch(reason){setError(reason instanceof Error?reason.message:"Could not load participants")}},[code]);useEffect(()=>{void load();const timer=setInterval(load,2500);return()=>clearInterval(timer)},[load]);const act=async(id:string,action:string)=>{const response=await fetch(`/api/v1/meetings/${encodeURIComponent(code.toUpperCase())}/participants/${encodeURIComponent(id)}/${action}`,{method:"POST",headers:{"Content-Type":"application/json"},body:"{}"});const data=await response.json().catch(()=>({}));if(!response.ok)setError(data?.error?.message??"Action failed");await load()};const waiting=items.filter(p=>p.status==="WAITING_ROOM"),joined=items.filter(p=>p.status==="JOINED");return <aside className="host-panel"><header><div><strong>Participants</strong><span>{items.length} in this meeting</span></div><button onClick={onClose}>×</button></header>{error&&<p className="host-error">{error}</p>}<section><h2>WAITING ROOM <span>{waiting.length}</span></h2>{waiting.length===0?<p className="empty-list">No one is waiting</p>:waiting.map(p=><article key={p.id}><Avatar name={p.displayName}/><div><strong>{p.displayName}</strong><span>Waiting to join</span></div><button className="admit" onClick={()=>act(p.id,"admit")}>Admit</button><button className="reject" onClick={()=>act(p.id,"reject")}>Reject</button></article>)}</section><section><h2>IN THE MEETING <span>{joined.length}</span></h2>{joined.map(p=><article key={p.id}><Avatar name={p.displayName}/><div><strong>{p.displayName}</strong><span>{p.role.replace("_"," ")}</span></div>{p.role!=="HOST"&&<button onClick={()=>act(p.id,"mute")}>Mute</button>}{p.role==="MEMBER"&&<button onClick={()=>act(p.id,"promote")}>Make co-host</button>}{p.role!=="HOST"&&<button className="reject" onClick={()=>act(p.id,"remove")}>Remove</button>}</article>)}</section></aside>}
function Avatar({name}:{name:string}){return <span className="participant-avatar">{name.split(/\s+/).map(word=>word[0]).slice(0,2).join("").toUpperCase()}</span>}
function RoomState({code}:{code:string}){return <main className="room-page"><div className="room-brand"><Brand/></div><section className="room-state"><div className="waiting-pulse"><span>AU</span></div><p>WAITING ROOM</p><h1>The host will let you in soon</h1><span>This page updates automatically. Your camera and microphone remain off while you wait.</span><div><b>Meeting code</b><strong>{code.toUpperCase()}</strong></div><Link href="/">Leave and return to dashboard</Link></section><footer><i/> Securely connected to Xpace · Jakarta region</footer></main>}
function MessageState({code,title,message}:{code:string;title:string;message:string}){return <main className="room-page"><div className="room-brand"><Brand/></div><section className="room-state"><div className="room-error">!</div><p>MEETING NOTICE</p><h1>{title}</h1><span>{message}</span><Link href={`/meet/${encodeURIComponent(code)}/prejoin`}>Return to device preview</Link></section></main>}
function Brand(){return <><span><i/></span><b>Xpace</b></>}
