"use client";

import { ChangeEvent, DragEvent, FormEvent, ReactNode, useEffect, useMemo, useRef, useState } from "react";
import styles from "./drive.module.css";

type DriveNode={id:string;parentId?:string;kind:"FILE"|"FOLDER";name:string;contentType?:string;sizeBytes:number;version:number;permission:string;retentionUntil?:string;updatedAt:string};
type DirectoryUser={id:string;username:string;displayName:string};
type DriveVersion={version:number;contentType:string;sizeBytes:number;createdAt:string};
type Filter="all"|"recent"|"shared";
type View="list"|"grid";
type Sort="name"|"updated"|"size";

export default function DrivePage(){
  const[nodes,setNodes]=useState<DriveNode[]>([]),[path,setPath]=useState<DriveNode[]>([]),[error,setError]=useState(""),[notice,setNotice]=useState(""),[used,setUsed]=useState(0),[users,setUsers]=useState<DirectoryUser[]>([]),[loading,setLoading]=useState(true),[uploading,setUploading]=useState(false),[dragging,setDragging]=useState(false);
  const[filter,setFilter]=useState<Filter>("all"),[view,setView]=useState<View>("list"),[sort,setSort]=useState<Sort>("name"),[query,setQuery]=useState(""),[menuId,setMenuId]=useState(""),[newFolderOpen,setNewFolderOpen]=useState(false),[folderName,setFolderName]=useState("");
  const[shareTarget,setShareTarget]=useState<DriveNode|null>(null),[shareUser,setShareUser]=useState(""),[sharePermission,setSharePermission]=useState("VIEW"),[historyTarget,setHistoryTarget]=useState<DriveNode|null>(null),[versions,setVersions]=useState<DriveVersion[]>([]);
  const[recentCutoff]=useState(()=>Date.now()-30*24*60*60*1000);
  const fileRef=useRef<HTMLInputElement>(null);
  const parent=path.at(-1)?.id??"";
  function roomContext(){return new URLSearchParams(window.location.search).get("roomId")??""}
  async function load(id=""){setLoading(true);setError("");const params=new URLSearchParams();if(id)params.set("parentId",id);const room=roomContext();if(room)params.set("roomId",room);const response=await fetch(`/api/v1/drive/nodes${params.size?`?${params}`:""}`),data=await response.json().catch(()=>({}));setLoading(false);if(!response.ok){setError(data?.error?.message??"Could not load Drive");return}setNodes(data.nodes??[]);setUsed(data.quota?.usedBytes??0)}
  useEffect(()=>{let active=true;const urlParams=new URLSearchParams(window.location.search),params=new URLSearchParams(),room=urlParams.get("roomId")??"",search=urlParams.get("search")??"";if(room)params.set("roomId",room);void Promise.all([fetch(`/api/v1/drive/nodes${params.size?`?${params}`:""}`),fetch("/api/v1/directory/users")]).then(async([driveResponse,directoryResponse])=>{const[driveData,directoryData]=await Promise.all([driveResponse.json().catch(()=>({})),directoryResponse.json().catch(()=>({}))]);if(!driveResponse.ok)throw new Error(driveData?.error?.message??"Could not load Drive");if(active){if(search)setQuery(search);setNodes(driveData.nodes??[]);setUsed(driveData.quota?.usedBytes??0);if(directoryResponse.ok)setUsers(directoryData.users??[])}}).catch(reason=>{if(active)setError(reason instanceof Error?reason.message:"Could not load Drive")}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[]);
  const visible=useMemo(()=>{const needle=query.trim().toLowerCase();return nodes.filter(item=>(!needle||item.name.toLowerCase().includes(needle))&&(filter!=="shared"||item.permission!=="OWNER")&&(filter!=="recent"||new Date(item.updatedAt).getTime()>=recentCutoff)).sort((a,b)=>{if(a.kind!==b.kind)return a.kind==="FOLDER"?-1:1;if(sort==="updated")return new Date(b.updatedAt).getTime()-new Date(a.updatedAt).getTime();if(sort==="size")return b.sizeBytes-a.sizeBytes;return a.name.localeCompare(b.name)})},[nodes,query,filter,sort,recentCutoff]);
  const folders=visible.filter(item=>item.kind==="FOLDER"),files=visible.filter(item=>item.kind==="FILE");
  async function createFolder(event:FormEvent){event.preventDefault();const response=await fetch("/api/v1/drive/folders",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:folderName,parentId:parent,roomId:roomContext()})}),data=await response.json().catch(()=>({}));if(!response.ok){setError(data?.error?.message??"Could not create folder");return}setNodes(items=>[data.node,...items]);setFolderName("");setNewFolderOpen(false);setNotice(`Folder “${data.node.name}” created.`)}
  async function upload(file?:File){if(!file)return;setUploading(true);setError("");setNotice("");const form=new FormData();form.append("file",file);form.append("parentId",parent);form.append("roomId",roomContext());const response=await fetch("/api/v1/drive/files",{method:"POST",body:form}),data=await response.json().catch(()=>({}));setUploading(false);if(!response.ok){setError(data?.error?.message??"Could not upload file");return}setNodes(items=>[data.node,...items]);setUsed(value=>value+data.node.sizeBytes);setNotice(`${data.node.name} uploaded.`)}
  async function chooseUpload(event:ChangeEvent<HTMLInputElement>){const file=event.target.files?.[0];event.target.value="";await upload(file)}
  async function drop(event:DragEvent){event.preventDefault();setDragging(false);await upload(event.dataTransfer.files?.[0])}
  async function open(item:DriveNode){setMenuId("");if(item.kind==="FOLDER"){setPath(items=>[...items,item]);await load(item.id);return}const response=await fetch(`/api/v1/drive/nodes/${item.id}/download`),data=await response.json().catch(()=>({}));if(response.ok&&data.url)window.open(data.url,"_blank","noopener,noreferrer");else setError(data?.error?.message??"Could not open file")}
  async function navigate(index:number){const next=index<0?[]:path.slice(0,index+1);setPath(next);await load(next.at(-1)?.id??"")}
  async function remove(item:DriveNode){setMenuId("");if(!window.confirm(`Move “${item.name}” to trash?`))return;const response=await fetch(`/api/v1/drive/nodes/${item.id}`,{method:"DELETE"});if(response.ok){setNodes(items=>items.filter(node=>node.id!==item.id));setNotice(`${item.name} moved to trash.`)}else setError("Could not remove item")}
  async function rename(item:DriveNode){setMenuId("");const name=window.prompt("Rename item",item.name)?.trim();if(!name||name===item.name)return;const response=await fetch(`/api/v1/drive/nodes/${item.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({name,parentId:item.parentId??null})});if(response.ok){setNodes(items=>items.map(node=>node.id===item.id?{...node,name,version:node.version+1}:node));setNotice(`Renamed to ${name}.`)}else setError("Could not rename item")}
  async function move(item:DriveNode){setMenuId("");const targets=nodes.filter(node=>node.kind==="FOLDER"&&node.id!==item.id);const target=window.prompt(`Move to folder ID (blank for My Drive):\n${targets.map(folder=>`${folder.name}: ${folder.id}`).join("\n")}`);if(target===null)return;const response=await fetch(`/api/v1/drive/nodes/${item.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:item.name,parentId:target.trim()||null})});if(response.ok){setNodes(items=>items.filter(node=>node.id!==item.id));setNotice(`${item.name} moved.`)}else setError("Could not move item")}
  async function share(event:FormEvent){event.preventDefault();if(!shareTarget)return;const response=await fetch(`/api/v1/drive/nodes/${shareTarget.id}/shares/${shareUser}`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({permission:sharePermission})});if(!response.ok){setError("Could not share item");return}setNotice(`${shareTarget.name} shared.`);setShareTarget(null);setShareUser("")}
  async function newVersion(item:DriveNode){setMenuId("");const input=document.createElement("input");input.type="file";input.onchange=async()=>{const file=input.files?.[0];if(!file)return;const form=new FormData();form.append("file",file);const response=await fetch(`/api/v1/drive/nodes/${item.id}/versions`,{method:"POST",body:form}),data=await response.json().catch(()=>({}));if(response.ok){setNodes(items=>items.map(node=>node.id===item.id?{...node,version:data.version,sizeBytes:file.size,updatedAt:new Date().toISOString()}:node));setNotice(`New version of ${item.name} uploaded.`)}else setError("Could not upload version")};input.click()}
  async function showHistory(item:DriveNode){setMenuId("");const response=await fetch(`/api/v1/drive/nodes/${item.id}/versions`),data=await response.json().catch(()=>({}));if(!response.ok){setError("Could not load versions");return}setVersions(data.versions??[]);setHistoryTarget(item)}
  async function restore(version:number){if(!historyTarget)return;const response=await fetch(`/api/v1/drive/nodes/${historyTarget.id}/versions/${version}/restore`,{method:"POST"}),data=await response.json().catch(()=>({}));if(response.ok){setNodes(items=>items.map(node=>node.id===historyTarget.id?{...node,version:data.version,updatedAt:new Date().toISOString()}:node));setNotice(`Version ${version} restored.`);setHistoryTarget(null)}else setError("Could not restore version")}
  return <main className={styles.page} onDragOver={event=>{event.preventDefault();setDragging(true)}} onDragLeave={event=>{if(event.currentTarget===event.target)setDragging(false)}} onDrop={event=>void drop(event)}>
    {dragging&&<div className={styles.dropzone}><FileGlyph item={placeholder("FILE")}/><strong>Drop a file to upload</strong><span>It will be added to {path.at(-1)?.name??"My Drive"}</span></div>}
    <header className={styles.titlebar}><div><p>XSPACE DRIVE</p><h1>Files</h1><span>Organize, share, and securely access workspace content.</span></div><button className={styles.uploadPrimary} onClick={()=>fileRef.current?.click()} disabled={uploading}>{uploading?"Uploading…":"＋ Upload"}</button><input ref={fileRef} type="file" hidden onChange={event=>void chooseUpload(event)}/></header>
    {(error||notice)&&<div className={error?styles.error:styles.notice} role={error?"alert":"status"}>{error||notice}<button onClick={()=>{setError("");setNotice("")}}>×</button></div>}
    <section className={styles.driveShell}>
      <aside className={styles.driveNav}><button className={styles.newButton} onClick={()=>setNewFolderOpen(true)}>＋ New folder</button><nav aria-label="Drive navigation"><button className={filter==="all"?styles.active:""} onClick={()=>setFilter("all")}><NavIcon name="drive"/>My Drive <span>{nodes.length}</span></button><button className={filter==="recent"?styles.active:""} onClick={()=>setFilter("recent")}><NavIcon name="clock"/>Recent</button><button className={filter==="shared"?styles.active:""} onClick={()=>setFilter("shared")}><NavIcon name="users"/>Shared with me</button></nav><div className={styles.storage}><div><strong>Storage</strong><span>{storagePercent(used)}% used</span></div><i><b style={{width:`${storagePercent(used)}%`}}/></i><p>{formatBytes(used)} of 10 GB</p></div></aside>
      <div className={styles.browser}>
        <div className={styles.browserTop}><div className={styles.breadcrumb}><button onClick={()=>void navigate(-1)}>My Drive</button>{path.map((folder,index)=><span key={folder.id}>› <button onClick={()=>void navigate(index)}>{folder.name}</button></span>)}</div><label className={styles.search}><NavIcon name="search"/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search in this folder" aria-label="Search Drive"/></label></div>
        <div className={styles.controls}><span>{visible.length} {visible.length===1?"item":"items"}</span><label>Sort<select value={sort} onChange={event=>setSort(event.target.value as Sort)}><option value="name">Name</option><option value="updated">Last modified</option><option value="size">Size</option></select></label><div className={styles.viewToggle}><button className={view==="list"?styles.active:""} aria-label="List view" onClick={()=>setView("list")}><NavIcon name="list"/></button><button className={view==="grid"?styles.active:""} aria-label="Grid view" onClick={()=>setView("grid")}><NavIcon name="grid"/></button></div></div>
        <div className={styles.content}>{loading?<div className={styles.empty}><i/><strong>Loading your Drive…</strong></div>:visible.length===0?<div className={styles.empty}><FileGlyph item={placeholder("FOLDER")}/><strong>{query?"No matching files":"This folder is empty"}</strong><span>{query?"Try another search term.":"Upload a file or create a folder to get started."}</span></div>:view==="grid"?<div className={styles.cardGrid}>{visible.map(item=><ItemCard key={item.id} item={item} menuId={menuId} setMenuId={setMenuId} open={open} rename={rename} move={move} share={()=>{setMenuId("");setShareTarget(item)}} newVersion={newVersion} history={showHistory} remove={remove}/>)}</div>:<><div className={styles.folderSection}>{folders.length>0&&<><h2>Folders</h2><div className={styles.folderGrid}>{folders.map(item=><ItemCard key={item.id} item={item} compact menuId={menuId} setMenuId={setMenuId} open={open} rename={rename} move={move} share={()=>{setMenuId("");setShareTarget(item)}} newVersion={newVersion} history={showHistory} remove={remove}/>)}</div></>}</div>{files.length>0&&<div className={styles.fileTable}><div className={styles.tableHead}><span>Name</span><span>Access</span><span>Last modified</span><span>Size</span><span/></div>{files.map(item=><FileRow key={item.id} item={item} menuId={menuId} setMenuId={setMenuId} open={open} rename={rename} move={move} share={()=>{setMenuId("");setShareTarget(item)}} newVersion={newVersion} history={showHistory} remove={remove}/>)}</div>}</>}</div>
      </div>
    </section>
    {menuId&&<button className={styles.menuScrim} aria-label="Close item menu" onClick={()=>setMenuId("")}/>}
    {newFolderOpen&&<Dialog title="Create a folder" close={()=>setNewFolderOpen(false)}><form className={styles.dialogForm} onSubmit={createFolder}><label>Folder name<input autoFocus value={folderName} maxLength={255} onChange={event=>setFolderName(event.target.value)} placeholder="Untitled folder" required/></label><div><button type="button" onClick={()=>setNewFolderOpen(false)}>Cancel</button><button>Create folder</button></div></form></Dialog>}
    {shareTarget&&<Dialog title={`Share “${shareTarget.name}”`} close={()=>setShareTarget(null)}><form className={styles.dialogForm} onSubmit={share}><label>Workspace member<select value={shareUser} onChange={event=>setShareUser(event.target.value)} required><option value="">Select a person…</option>{users.map(user=><option value={user.id} key={user.id}>{user.displayName} (@{user.username})</option>)}</select></label><label>Permission<select value={sharePermission} onChange={event=>setSharePermission(event.target.value)}><option value="VIEW">Can view</option><option value="EDIT">Can edit</option></select></label><div><button type="button" onClick={()=>setShareTarget(null)}>Cancel</button><button>Share</button></div></form></Dialog>}
    {historyTarget&&<Dialog title={`Version history · ${historyTarget.name}`} close={()=>setHistoryTarget(null)}><div className={styles.versionList}>{versions.map(entry=><article key={entry.version}><div><strong>Version {entry.version}</strong><span>{formatDate(entry.createdAt)} · {formatBytes(entry.sizeBytes)}</span></div><button disabled={entry.version===historyTarget.version} onClick={()=>void restore(entry.version)}>{entry.version===historyTarget.version?"Current":"Restore"}</button></article>)}</div></Dialog>}
  </main>;
}

type ItemActions={item:DriveNode;menuId:string;setMenuId:(value:string)=>void;open:(item:DriveNode)=>Promise<void>;rename:(item:DriveNode)=>Promise<void>;move:(item:DriveNode)=>Promise<void>;share:()=>void;newVersion:(item:DriveNode)=>Promise<void>;history:(item:DriveNode)=>Promise<void>;remove:(item:DriveNode)=>Promise<void>};
function ItemCard(props:ItemActions&{compact?:boolean}){const{item,compact}=props;return <article className={`${styles.itemCard} ${compact?styles.compactCard:""}`} onDoubleClick={()=>void props.open(item)}><button className={styles.cardOpen} onClick={()=>void props.open(item)}><FileGlyph item={item}/><span><strong>{item.name}</strong><small>{item.kind==="FOLDER"?`${formatPermission(item.permission)} · Folder`:`${formatBytes(item.sizeBytes)} · v${item.version}`}</small></span></button><ItemMenu {...props}/></article>}
function FileRow(props:ItemActions){const{item}=props;return <article className={styles.fileRow} onDoubleClick={()=>void props.open(item)}><button className={styles.fileName} onClick={()=>void props.open(item)}><FileGlyph item={item}/><span><strong>{item.name}</strong><small>{fileType(item)}</small></span></button><span className={styles.permission}>{formatPermission(item.permission)}</span><time>{formatDate(item.updatedAt)}</time><span>{formatBytes(item.sizeBytes)}</span><ItemMenu {...props}/></article>}
function ItemMenu(props:ItemActions){const{item}=props,open=props.menuId===item.id;return <div className={styles.itemMenu}><button className={styles.more} aria-label={`Actions for ${item.name}`} aria-expanded={open} onClick={event=>{event.stopPropagation();props.setMenuId(open?"":item.id)}}>•••</button>{open&&<div className={styles.menu}><button onClick={()=>void props.open(item)}>{item.kind==="FOLDER"?"Open folder":"Open file"}</button><button onClick={props.share}>Share</button><button onClick={()=>void props.rename(item)}>Rename</button><button onClick={()=>void props.move(item)}>Move</button>{item.kind==="FILE"&&<><button onClick={()=>void props.newVersion(item)}>Upload new version</button><button onClick={()=>void props.history(item)}>Version history</button></>}<button className={styles.danger} onClick={()=>void props.remove(item)}>Move to trash</button></div>}</div>}
function Dialog({title,close,children}:{title:string;close:()=>void;children:ReactNode}){return <div className={styles.backdrop} onMouseDown={event=>{if(event.currentTarget===event.target)close()}}><section className={styles.dialog} role="dialog" aria-modal="true" aria-label={title}><header><h2>{title}</h2><button onClick={close} aria-label="Close dialog">×</button></header>{children}</section></div>}
function FileGlyph({item}:{item:DriveNode}){const folder=item.kind==="FOLDER",tone=fileTone(item);return <span className={`${styles.fileGlyph} ${styles[tone]}`}>{folder?<svg viewBox="0 0 24 24"><path d="M3 6.5A2.5 2.5 0 0 1 5.5 4H10l2 2h6.5A2.5 2.5 0 0 1 21 8.5v8A2.5 2.5 0 0 1 18.5 19h-13A2.5 2.5 0 0 1 3 16.5Z"/></svg>:<svg viewBox="0 0 24 24"><path d="M6 3h8l4 4v14H6Z"/><path d="M14 3v5h5"/></svg>}</span>}
function NavIcon({name}:{name:"drive"|"clock"|"users"|"search"|"list"|"grid"}){const paths={drive:<><rect x="3" y="4" width="18" height="16" rx="3"/><circle cx="12" cy="12" r="3"/></>,clock:<><circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/></>,users:<><circle cx="9" cy="8" r="3"/><path d="M3 20v-2a5 5 0 0 1 5-5h2a5 5 0 0 1 5 5v2M17 6a3 3 0 0 1 0 6M18 14a4 4 0 0 1 3 4v2"/></>,search:<><circle cx="10" cy="10" r="6"/><path d="m15 15 5 5"/></>,list:<path d="M8 6h12M8 12h12M8 18h12M4 6h.01M4 12h.01M4 18h.01"/>,grid:<><rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/></>};return <svg viewBox="0 0 24 24" aria-hidden="true">{paths[name]}</svg>}
function placeholder(kind:"FILE"|"FOLDER"):DriveNode{return{id:"",kind,name:"",sizeBytes:0,version:1,permission:"",updatedAt:""}}
function fileTone(item:DriveNode){if(item.kind==="FOLDER")return"folder";if(item.contentType?.includes("pdf"))return"pdf";if(item.contentType?.startsWith("image/"))return"image";if(item.contentType?.includes("sheet")||/\.xlsx?$|\.csv$/i.test(item.name))return"sheet";if(item.contentType?.includes("word")||/\.docx?$/i.test(item.name))return"doc";return"generic"}
function fileType(item:DriveNode){const extension=item.name.split(".").pop();return extension&&extension!==item.name?`${extension.toUpperCase()} file`:(item.contentType||"File")}
function formatPermission(value:string){return value==="OWNER"?"Owned by me":value==="EDIT"?"Can edit":"Shared with me"}
function formatDate(value:string){return new Intl.DateTimeFormat("en",{dateStyle:"medium"}).format(new Date(value))}
function formatBytes(value:number){if(value<1024)return`${value} B`;if(value<1024**2)return`${(value/1024).toFixed(1)} KB`;if(value<1024**3)return`${(value/1024**2).toFixed(1)} MB`;return`${(value/1024**3).toFixed(1)} GB`}
function storagePercent(value:number){return Math.min(100,Math.max(0,Math.round(value/(10*1024**3)*100)))}
