"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import styles from "./scim.module.css";

type Configuration={configured:boolean;enabled:boolean;rotatedAt?:string;baseUrl:string};

export default function SCIMPage(){
  const[configuration,setConfiguration]=useState<Configuration|null>(null),[token,setToken]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
  async function load(){const response=await fetch("/api/v1/admin/identity/scim");const data=await response.json().catch(()=>({}));if(response.ok)setConfiguration(data);else setMessage(data?.error?.message??"Could not load SCIM configuration")}
  useEffect(()=>{let active=true;void fetch("/api/v1/admin/identity/scim").then(async response=>{const data=await response.json().catch(()=>({}));if(!active)return;if(response.ok)setConfiguration(data);else setMessage(data?.error?.message??"Could not load SCIM configuration")});return()=>{active=false}},[]);
  async function rotate(){if(configuration?.configured&&!window.confirm("Rotate the SCIM token? The previous token will stop working immediately."))return;setBusy(true);const response=await fetch("/api/v1/admin/identity/scim",{method:"POST"});const data=await response.json().catch(()=>({}));setBusy(false);if(response.ok){setToken(data.token);setMessage("SCIM token created. Copy it now; it will not be shown again.");await load()}else setMessage(data?.error?.message??"Could not rotate SCIM token")}
  async function disable(){if(!window.confirm("Disable SCIM provisioning for this workspace?"))return;setBusy(true);const response=await fetch("/api/v1/admin/identity/scim",{method:"DELETE"});setBusy(false);if(response.ok){setToken("");setMessage("SCIM provisioning disabled.");await load()}else setMessage("Could not disable SCIM")}
  return <main className={styles.page}><header><div><p>XSPACE ADMIN · PROVISIONING</p><h1>SCIM 2.0</h1><span>Provision and deactivate tenant users and groups from your identity provider.</span></div><nav><Link href="/admin">Dashboard</Link><Link href="/admin/roles">Roles</Link><Link href="/admin/settings">Identity settings</Link></nav></header>{message&&<div className={styles.notice} role="status">{message}</div>}<section className={styles.card}><div className={styles.status}><span className={configuration?.enabled?styles.enabled:""}>↻</span><div><h2>Provisioning endpoint</h2><p>{configuration?.enabled?"Enabled and accepting authenticated SCIM requests.":"Not enabled for this workspace."}</p></div><b>{configuration?.enabled?"ENABLED":"DISABLED"}</b></div>{configuration?<><label>Tenant base URL<input readOnly value={configuration.baseUrl}/><button onClick={()=>void navigator.clipboard.writeText(configuration.baseUrl)}>Copy</button></label>{configuration.rotatedAt&&<small>Token last rotated {new Intl.DateTimeFormat("en",{dateStyle:"medium",timeStyle:"short"}).format(new Date(configuration.rotatedAt))}</small>}<div className={styles.actions}><button onClick={()=>void rotate()} disabled={busy}>{configuration.configured?"Rotate bearer token":"Generate bearer token"}</button>{configuration.enabled&&<button className={styles.danger} onClick={()=>void disable()} disabled={busy}>Disable SCIM</button>}</div></>:<p>Loading provisioning configuration…</p>}</section>{token&&<section className={styles.secret}><h2>New bearer token</h2><p>This secret is displayed once. Store it in your identity provider now.</p><div><code>{token}</code><button onClick={()=>void navigator.clipboard.writeText(token).then(()=>setMessage("Bearer token copied."))}>Copy token</button></div></section>}<section className={styles.guide}><h2>Provider setup</h2><ol><li>Generate a bearer token and copy the tenant base URL.</li><li>Configure the values in Microsoft Entra ID, Okta, or another SCIM 2.0 client.</li><li>Enable Users and Groups provisioning with create, replace, and deactivate operations.</li><li>Use <code>userName</code> as the matching attribute.</li></ol><p>SCIM-created users receive the MEMBER base role. Delegate additional access through Xspace custom roles.</p></section></main>
}
